export type BookSegment = string | { text: string; type: "story" | "commentary" };

export const books: Record<string, { title: string; content: BookSegment[] }> = {
    "security-plus": {
        title: "CompTIA Security+ Study Guide",
        content: [
            // --- CHAPTER 1 ---
            "CHAPTER 1: SECURITY CONTROLS (THE BRITISH EDITION)",
            { text: "Rewritten in Everyday Modern British English (Now with Extra Banter)", type: "commentary" },
            { text: "Note: This guide breaks down the exam objectives for Domain 1.0 using proper British slang to make it stick better than a biscuit in tea.", type: "commentary" },
            "INTRODUCTION",
            { text: "In today's world, keeping your digital gaff (place) safe is a massive job. You can't just slap a rusty padlock on the front door and head down the pub for a pint and a packet of crisps; you need proper layers of protection.", type: "story" },
            { text: "Security controls are the bread and butter (or fish and chips) of any decent security setup. They help you stop things going pear-shaped (wrong), spot when some chancer is trying to pull a fast one, and make sure you aren't breaking the law.", type: "story" },
            { text: "This chapter covers the first exam objective in Domain 1.0. We'll have a butcher's (look) at the different types of controls—Technical, Managerial, Operational, and Physical.", type: "story" },
            { text: "Then we'll suss out what they actually do—like stopping trouble before it starts (Preventive) or mopping up the spilt milk afterwards (Corrective).", type: "story" },
            { text: "Security controls are just the tools and rules companies use to protect themselves. Think of it like securing your house: you lock the door (Preventive), put up a \"Beware of the Mother-in-Law\" sign (Deterrent), and maybe install a camera to see which neighbour is pinching your milk (Detective).", type: "commentary" },
            "CONTROL CATEGORIES (THE BIG FOUR)",
            { text: "There are four main buckets we throw these controls into. Each one handles a different part of the business to keep things running tickety-boo.", type: "story" },
            "1. Technical Controls (The Techy Stuff)",
            { text: "This is the gear implemented by the IT crowd. It's all about using wizardry and technology to stop the bad actors (hackers in hoodies) from getting into your systems.", type: "story" },
            { text: "Firewalls: These are your digital bouncers. They stand at the door of your network, arms folded, checking everyone's ID. If you're not on the list or your trainers look a bit dodgy, you're not getting in.", type: "story" },
            { text: "Data Encryption: This turns your important info into complete gobbledygook (nonsense). If some wrong 'un manages to nick (steal) your data, they won't be able to read it without the secret key.", type: "story" },
            { text: "Technical controls are software or hardware tools. If it involves code, flashing lights, or a machine doing the heavy lifting, it's usually a Technical control.", type: "commentary" },
            "2. Managerial Controls (The Suits)",
            { text: "This is the stuff handled by the bigwigs (bosses). It involves risk assessments, writing the rulebook, and making sure everyone is towing the line.", type: "story" },
            { text: "Performance Reviews: Checking if staff are pulling their weight or just pretending to work while playing Solitaire.", type: "story" },
            { text: "Risk Assessments: This is basically doom-scrolling for business. You sit down and work out what could go wrong. \"What if the servers catch fire?\" \"What if Dave from Accounts clicks a link for 'Free iPhones'?\"", type: "story" },
            { text: "Managerial controls are the \"paperwork\" and \"decisions\" side of security. Policies, laws, huge PDF documents nobody reads, and reviews fall here.", type: "commentary" },
            "3. Operational Controls (The Daily Grind)",
            { text: "These are the things done by actual humans on a day-to-day basis. It's the practical stuff to keep the lights on and the data safe.", type: "story" },
            { text: "Incident Response Procedures: The master plan for when the muck hits the fan. If you get hacked, this is the step-by-step guide on how to fix it without running around like a headless chicken screaming \"We're doomed!\"", type: "story" },
            { text: "Security Awareness Training: Teaching staff not to be daft. It's showing them how to spot a phishing email so Barry in Sales doesn't download a virus thinking he's won the Nigerian lottery.", type: "story" },
            { text: "Operational controls are executed by people. If a human has to get off their backside and do something (like attend training or follow a checklist), it's Operational.", type: "commentary" },
            "4. Physical Controls (Bricks and Mortar)",
            { text: "This is the stuff you can actually kick (though we don't recommend it). It protects the real-world assets—buildings, servers, and staff—from being tampered with or stolen.", type: "story" },
            { text: "Access Control Vestibule: A fancy name for a \"mantrap.\" It sounds like something from a spy film, but it's just a small room with two doors. Stops sneaky people tailgating you into the office to steal the biscuits.", type: "story" },
            { text: "If you can touch it, it's a Physical control. Fences, locks, cameras, guards, dogs, moats with sharks (optional).", type: "commentary" },
            
            // --- CHAPTER 2 ---
            "CHAPTER 2: FUNDAMENTAL SECURITY CONCEPTS",
            { text: "Rewritten in Everyday Modern British English. Note: We're diving into Domain 1.0, Objective 1.2. Grab a brew, this covers the bread and butter of keeping things secure.", type: "commentary" },
            "INTRODUCTION",
            { text: "Right then, Chapter 1 was about the tools; Chapter 2 is about the ideas. We're looking at the big concepts that stop your digital life going down the swanny.", type: "story" },
            { text: "We'll cover the CIA Triad (not the spies), Zero Trust (trusting nobody), and Deception technology (setting traps for the bad guys).", type: "story" },
            "THE CIA TRIAD (THE HOLY TRINITY)",
            { text: "In the security world, everything revolves around three things. If you mess one of these up, you're in for a right pickle.", type: "story" },
            { text: "Confidentiality: Keeping your secrets secret. It ensures that only the people who should see the data can see it. It's like whispering gossip to your best mate and making sure the town busybody didn't hear.", type: "story" },
            { text: "Integrity: Making sure nobody has messed with your data. If you send an email saying \"Pay Dave £10\", you don't want someone changing it to \"Pay Dave £10,000\". Integrity uses things like hashing to prove the data hasn't been fiddled with.", type: "story" },
            { text: "Availability: Making sure the systems are actually working when you need them. It's no good having the most secure website in the world if it crashes every time someone tries to log in.", type: "story" },
            { text: "Clarification: Confidentiality = No peeking. Integrity = No touching. Availability = No crashing.", type: "commentary" },
            "NON-REPUDIATION",
            { text: "This is a fancy way of saying \"You can't deny you did it.\" If you sign a contract or send a secure email with a digital signature, you can't turn around later and say, \"Wasn't me, gov.\" It provides proof of who did what.", type: "story" },
            "AAA (THE BOUNCER PROTOCOLS)",
            { text: "If you want to get into a club (or a server), you have to go through the AAA process.", type: "story" },
            { text: "Authentication: This is the bouncer asking, \"Who are you?\" You show your ID (username) and prove it's you (password/PIN).", type: "story" },
            { text: "Authorization: The bouncer checks the clipboard. \"Are you on the list?\" Just because you are Dave doesn't mean you're allowed in the VIP area. This decides what you can actually do once you're in.", type: "story" },
            { text: "Accounting: The bouncer writes down what time you came in and what time you left. It's logging everything so if something goes missing, they know who was in the building.", type: "story" },
            { text: "Tech check: We use protocols like RADIUS (Remote Authentication Dial-In User Service) and TACACS+ to handle this stuff securely.", type: "commentary" },
            "ZERO TRUST (TRUST NO ONE)",
            { text: "The old way of thinking was: \"If you're inside the office building, you must be a good guy.\" The new way is Zero Trust.", type: "story" },
            { text: "It basically means: \"I don't care if you're the CEO or the cleaner, and I don't care if you're in the office or working from a café in Benidorm. I'm checking your ID every single time you try to open a file.\" Never trust, always verify.", type: "story" },
            "PHYSICAL SECURITY (BOLLARDS AND BLOKES)",
            { text: "This is about stopping people physically breaking in.", type: "story" },
            { text: "Bollards: Those sturdy concrete or metal posts you see outside buildings. They stop someone driving a lorry through the front window.", type: "story" },
            { text: "Access Control Vestibule: The posh word for a mantrap. A small room with two doors; one locks before the other opens. Stops tailgaters.", type: "story" },
            { text: "CCTV: Cameras everywhere. Smile, you're on candid camera.", type: "story" },
            { text: "Lighting: Bad guys hate bright lights. Light up the car park like a Christmas tree to scare them off.", type: "story" },
            { text: "Sensors: Things that go \"beep\" when you walk past. Infrared (heat), Microwave (movement), Ultrasonic (sound).", type: "story" },
            "DECEPTION TECHNOLOGY (SETTING TRAPS)",
            { text: "Sometimes the best defence is a trap.", type: "story" },
            { text: "Honeypot: A fake server that looks full of juicy data but is actually a trap. You leave it open on purpose to lure hackers in so you can watch what they do. Like leaving a fake wallet on the pavement to see who nicks it.", type: "story" },
            { text: "Honeynet: A whole network of honeypots. A minefield for hackers.", type: "story" },
            { text: "Honeyfile: A file named \"Passwords.txt\" on your desktop. It's fake, but if anyone opens it, an alarm goes off. Gotcha!", type: "story" },
            "CHAPTER 2 REVIEW QUESTIONS",
            { text: "1. An IT administrator has been tasked by the boss to investigate the latest attack methods being used by a bad actor. Which of the following would be the BEST resource to use?\nA. MITRE ATT&CK\nB. A honeyfile\nC. A honeypot\nD. A CVE list", type: "story" },
            { text: "Answer: C. A honeypot is set up specifically to lure attackers so you can study their moves without risking your real systems.", type: "commentary" },
            { text: "2. What type of system is able to track users' access if the authentication method uses 802.1x?\nA. Federation Services\nB. Kerberos\nC. OAuth\nD. RADIUS", type: "story" },
            { text: "Answer: D. RADIUS is the go-to protocol for tracking user access in this scenario.", type: "commentary" },
            { text: "3. Which of the following can be used to provide non-repudiation?\nA. Asymmetric encryption\nB. Symmetric encryption\nC. A public key\nD. A SAML token", type: "story" },
            { text: "Answer: A. Asymmetric encryption (using digital signatures) proves exactly who sent the message. You can't deny it!", type: "commentary" },
            { text: "4. An international bank suffered an insider attack where $100,000 was pinched. The security team needs to find the culprit. Which is the BEST source of information?\nA. The system log\nB. The application log\nC. An audit trail\nD. The DNS log", type: "story" },
            { text: "Answer: C. An audit trail keeps a chronological record of who did what. It's the paper trail that catches the thief.", type: "commentary" },
            { text: "5. Which of the following security tools presents itself as a prized target, uses dummy data, and helps track attackers?\nA. Honeypot\nB. A honeyfile\nC. A honeytoken\nD. PAM", type: "story" },
            { text: "Answer: C. A honeytoken is a specific piece of fake data (like a fake database entry) that looks valuable but triggers an alarm when touched.", type: "commentary" },

            // --- CHAPTER 3 ---
            "CHAPTER 3: CHANGE MANAGEMENT (THE FUN POLICE)",
            { text: "Note: This covers Exam Objective 1.3. Why we can't just change settings willy-nilly.", type: "commentary" },
            "INTRODUCTION",
            { text: "Change is inevitable, like rain on a Bank Holiday. But in IT, if you just change things without a plan, everything goes pear-shaped very quickly. Change Management is the boring but essential process of making sure updates don't break the whole company.", type: "story" },
            "THE PROCESS",
            { text: "You can't just decide to update the server because you feel like it. You have to follow the rules.", type: "story" },
            { text: "Approval Process: You have to ask permission. You write down what you want to do and why.", type: "story" },
            { text: "CAB (Change Advisory Board): A group of serious people (The Fun Police) who sit around a table and decide if your idea is brilliant or rubbish. They look at the risks and give the thumbs up (or down).", type: "story" },
            { text: "Impact Analysis: Asking \"What happens if we press this button?\" You need to know who will be affected.", type: "story" },
            { text: "Backout Plan: The \"Undo\" button. If the update destroys the database, how do you go back to how it was 10 minutes ago? Crucial.", type: "story" },
            { text: "Maintenance Window: The time you're allowed to do the work. Usually 3 AM on a Sunday when nobody is working, so if you break it, nobody notices immediately.", type: "story" },
            "DOCUMENTATION",
            { text: "If you didn't write it down, it didn't happen.", type: "story" },
            { text: "Network Diagrams: Maps of where all the cables and servers go. Keep them updated or you'll be lost.", type: "story" },
            { text: "Version Control: Keeping track of changes to code or documents (v1.0, v1.1, v2.0). Stops people overwriting each other's work.", type: "story" },
            "CHAPTER 3 REVIEW QUESTIONS",
            { text: "1. What component of change management is essential for ensuring that security operations are not adversely affected by new implementations?\nA. Ownership\nB. Test results\nC. An approval process\nD. A backout plan", type: "story" },
            { text: "Answer: C. The approval process (specifically via the CAB) ensures that changes align with security goals before they happen.", type: "commentary" },
            { text: "2. Which of the following is the BEST solution for a cybersecurity team to implement to prevent employees from installing video games on company systems?\nA. Sandbox\nB. An allow list\nC. A block list\nD. Least privilege", type: "story" },
            { text: "Answer: B. An allow list (whitelist) is best because it only lets approved work apps run. Everything else (like games) is blocked by default.", type: "commentary" },
            { text: "3. When ensuring the accuracy of system representations, what practice reflects the actual network infrastructure?\nA. Regression testing\nB. Updating diagrams\nC. Data masking\nD. Version control", type: "story" },
            { text: "Answer: B. Updating diagrams ensures your maps match the territory.", type: "commentary" },

            // --- CHAPTER 4 ---
            "CHAPTER 4: CRYPTOGRAPHY (SECRET CODES)",
            { text: "Note: This covers Exam Objective 1.4. Turning English into gobbledygook.", type: "commentary" },
            "INTRODUCTION",
            { text: "Cryptography isn't just for spies; it's how the internet works. It ensures your credit card details don't get nicked when you buy stuff online.", type: "story" },
            "PKI (PUBLIC KEY INFRASTRUCTURE)",
            { text: "This is the system of digital certificates that proves who people are.", type: "story" },
            { text: "Keys: Think of a lock and key. Public Key: You give this to everyone. Private Key: You keep this secret. Never share it.", type: "story" },
            "ENCRYPTION TYPES",
            { text: "Symmetric Encryption: Using the same key to lock and unlock the box. It's fast and good for large amounts of data. Analogy: A house key.", type: "story" },
            { text: "Asymmetric Encryption: Using a pair of keys (Public and Private). It's slower but safer for sharing keys. Analogy: A postbox. Anyone can put a letter in (Public), but only the postman with the key can take letters out (Private).", type: "story" },
            "HASHING (DIGITAL FINGERPRINTS)",
            { text: "Hashing takes a file and turns it into a unique string of characters. One-Way: You can turn a file into a hash, but you can't turn the hash back into the file. You can't turn an omelette back into an egg.", type: "story" },
            { text: "Salting: Adding random data to a password before hashing it. It makes it much harder for hackers to crack passwords.", type: "story" },
            "OBFUSCATION & BLOCKCHAIN",
            { text: "Steganography: Hiding secret data inside an innocent picture or music file.", type: "story" },
            { text: "Blockchain: A digital ledger (record book) that is shared across thousands of computers. Immutable: Once you write something in the blockchain, you can't rub it out.", type: "story" },
            "CHAPTER 4 REVIEW QUESTIONS",
            { text: "1. What is the primary purpose of a private key in a Public Key Infrastructure (PKI)?\nA. The encryption of sensitive data\nB. Storing cryptographic keys\nC. Encrypting messages for secure transmission\nD. Decryption and digital signatures", type: "story" },
            { text: "Answer: D. The private key is for decrypting messages sent to you and creating digital signatures.", type: "commentary" },
            { text: "2. Which type of encryption employs a single key to encrypt substantial volumes of data?\nA. Hashing\nB. Asymmetric encryption\nC. Symmetric encryption\nD. A key exchange", type: "story" },
            { text: "Answer: C. Symmetric encryption uses one key and is fast enough for big data.", type: "commentary" },
            { text: "3. What technique involves transforming sensitive data, such as credit card numbers, into unique tokens that retain no intrinsic value?\nA. Obfuscation\nB. Salting\nC. Tokenization\nD. Steganography", type: "story" },
            { text: "Answer: C. Tokenization. It swaps the real data for a useless token.", type: "commentary" },

            // --- CHAPTER 5 ---
            "CHAPTER 5: THREAT ACTORS (THE BAD GUYS)",
            { text: "Note: This covers Domain 2.0, Objective 2.1. Know your enemy.", type: "commentary" },
            "THE LINE-UP",
            { text: "Nation State: Government-backed hackers. These folks have unlimited budgets, all the best toys, and are usually playing the long game (espionage).", type: "story" },
            { text: "Unskilled Attacker (Script Kiddies): The amateurs. They buy tools off the dark web or download scripts they don't understand. \"All the gear, no idea.\"", type: "story" },
            { text: "Hacktivists: Keyboard warriors with a cause. They hack for political or social reasons (like Anonymous).", type: "story" },
            { text: "Insider Threat: The traitor within. It could be Disgruntled Dave who got fired, or just Clumsy Colin who clicked a dodgy link. Hard to detect because they already have the keys to the building.", type: "story" },
            "MOTIVATIONS",
            { text: "Financial Gain: Pure greed. Ransomware, stealing credit cards. The most common reason.", type: "story" },
            { text: "Espionage: Spying. Usually Nation States trying to find out government secrets.", type: "story" },
            { text: "Revenge: Getting your own back. Usually an ex-employee who got the sack.", type: "story" },
            "CHAPTER 5 REVIEW QUESTIONS",
            { text: "1. Which threat actor is most likely to steal trade secrets for a competing company?\nA. A nation-state\nB. Unskilled attacker\nC. A hacktivist\nD. Organized crime", type: "story" },
            { text: "Answer: D. Organized crime (or sometimes Nation States/APTs) are usually the ones doing industrial espionage for money.", type: "commentary" },
            { text: "2. An attacker threatens to expose sensitive data unless you pay a massive sum. What is this?\nA. Blackmail\nB. Financial gain\nC. Ransomware attack\nD. Espionage", type: "story" },
            { text: "Answer: A. Blackmail (often linked to Ransomware). \"Pay up or else.\"", type: "commentary" },

            // --- CHAPTER 6 ---
            "CHAPTER 6: THREAT VECTORS (HOW THEY GET IN)",
            { text: "Note: This covers Exam Objective 2.2. The many ways to skin a cat.", type: "commentary" },
            "MESSAGE-BASED ATTACKS",
            { text: "Phishing: Sending dodgy emails pretending to be the bank or the CEO. \"Click here to claim your refund.\"", type: "story" },
            { text: "Smishing: Phishing via SMS (text message).", type: "story" },
            { text: "Vishing: Voice phishing. Someone ringing you up pretending to be \"Windows Support\" claiming you have a virus.", type: "story" },
            "SOCIAL ENGINEERING (HACKING THE HUMAN)",
            { text: "Why spend days cracking a firewall when you can just ask someone for their password?", type: "story" },
            { text: "Pretexting: Creating a fake scenario. \"Hi, I'm calling from IT, we need to sync your account...\"", type: "story" },
            { text: "Business Email Compromise (BEC): Taking over the boss's email account and telling accounts to \"pay this invoice urgently.\"", type: "story" },
            { text: "Watering Hole: Infecting a website that you know your target visits. Like poisoning the village well.", type: "story" },
            "CHAPTER 6 REVIEW QUESTIONS",
            { text: "1. You get an email from \"The Taxman\" asking for bank details for a refund. You reply, and your account gets emptied. What was this?\nA. Spear phishing\nB. Phishing\nC. Smishing\nD. Vishing", type: "story" },
            { text: "Answer: B. Phishing. A general attempt to trick you via email.", type: "commentary" },
            { text: "2. You type www.microsooft.com and land on a dodgy site. What is this?\nA. Brand impersonation\nB. Typosquatting\nC. Watering hole attack\nD. Whaling", type: "story" },
            { text: "Answer: B. Typosquatting (URL hijacking). Exploiting typos.", type: "commentary" },

            // --- CHAPTER 7 ---
            "CHAPTER 7: VULNERABILITIES (THE WEAK SPOTS)",
            { text: "Note: This covers Exam Objective 2.3. Where the cracks are.", type: "commentary" },
            "APPLICATION VULNERABILITIES",
            { text: "Buffer Overflow: Trying to pour a pint of beer into a shot glass. It spills over and makes a mess (crashes the system).", type: "story" },
            { text: "Injection Attacks (SQLi): Typing code into a website's search box to trick the database. \"Show me all users.\"", type: "story" },
            { text: "Cross-Site Scripting (XSS): Injecting malicious scripts into a trusted website.", type: "story" },
            "VIRTUALIZATION VULNERABILITIES",
            { text: "VM Escape: The nightmare scenario. Breaking out of a Virtual Machine and accessing the main Host server.", type: "story" },
            { text: "VM Sprawl: Creating too many VMs and losing track of them. You can't patch what you don't know exists.", type: "story" },
            "ZERO-DAY VULNERABILITY",
            { text: "A vulnerability that the software vendor doesn't know about yet. There is no patch. It's an open door for hackers until it's discovered and fixed.", type: "story" },
            "CHAPTER 7 REVIEW QUESTIONS",
            { text: "1. What is \"VM Escape\"?\nA. Enhancing performance\nB. Transferring VMs\nC. Attacker moves from VM to Host\nD. Creating templates", type: "story" },
            { text: "Answer: C. Breaking out of the VM to access the host system.", type: "commentary" },
            { text: "2. How do you prevent data breaches after unauthorized acquisition?\nA. Default settings\nB. Host-based firewalls\nC. Limit admin accounts\nD. Data Loss Prevention (DLP)", type: "story" },
            { text: "Answer: D. DLP systems detect and block sensitive data from leaving the network.", type: "commentary" },

            // --- CHAPTER 8 ---
            "CHAPTER 8: MALICIOUS ACTIVITY (SPOTTING THE ROT)",
            { text: "Note: This covers Exam Objective 2.4. Detecting when you've been done over.", type: "commentary" },
            "MALWARE TYPES",
            { text: "Ransomware: Encrypts your files and demands crypto payment. \"Pay up or lose your holiday photos.\"", type: "story" },
            { text: "Trojans: Looks like a useful app, acts like a spy. Gives hackers a \"backdoor\" into your PC.", type: "story" },
            { text: "Logic Bomb: Malware that waits for a specific time or event (like a disgruntled admin getting fired) to detonate.", type: "story" },
            { text: "Rootkits: Buries itself deep in the OS (kernel level) to hide from antivirus. Very nasty.", type: "story" },
            "PASSWORD ATTACKS",
            { text: "Brute Force: Trying every single combination. aaaa, aaab, aaac... Sledgehammer approach.", type: "story" },
            { text: "Credential Stuffing: Taking a list of leaked passwords from one breach (e.g., Netflix) and trying them on another site (e.g., Banking), hoping the user reused the password.", type: "story" },
            "CHAPTER 8 REVIEW QUESTIONS",
            { text: "1. Files are deleted every Monday at 9 AM. What is this?\nA. Logic bomb\nB. Buffer overflow\nC. Trojan\nD. Rootkit", type: "story" },
            { text: "Answer: A. Logic bomb. It triggers on a specific event (time).", type: "commentary" },
            { text: "2. Attackers use stolen credentials from one site to access another. What is this?\nA. SQL injection\nB. Phishing\nC. Credential stuffing\nD. Credential harvesting", type: "story" },
            { text: "Answer: C. Credential stuffing.", type: "commentary" },

            // --- CHAPTER 9 ---
            "CHAPTER 9: MITIGATION TECHNIQUES (FIXING IT)",
            { text: "Note: This covers Exam Objective 2.5. How to stop the bleeding.", type: "commentary" },
            "SEGMENTATION",
            { text: "VLANs: Virtual networks. Keeps Sales traffic separate from HR traffic.", type: "story" },
            { text: "Air Gap: Physically disconnecting a sensitive computer from the network. The ultimate segmentation.", type: "story" },
            "ACCESS CONTROL",
            { text: "Least Privilege: Give people only the access they need to do their job, and not a drop more. If you're a cleaner, you don't need the keys to the safe.", type: "story" },
            "MONITORING",
            { text: "SIEM: A system that collects logs from everywhere and looks for patterns. It's the \"Central Brain\" of security monitoring.", type: "story" },
            { text: "SOAR: Like SIEM, but it can actually do things automatically. If it sees a virus, it can isolate the computer without a human needing to click anything.", type: "story" },
            "CHAPTER 9 REVIEW QUESTIONS",
            { text: "1. How do you stop a user installing a game?\nA. Firewall\nB. IDS\nC. Application allow list\nD. Increase privileges", type: "story" },
            { text: "Answer: C. Application allow list. If the game isn't on the list, it won't run.", type: "commentary" },
            { text: "2. After a malware attack, what detects threats on the endpoint?\nA. EDR\nB. SIEM\nC. SOAR\nD. Scanner", type: "story" },
            { text: "Answer: A. EDR (Endpoint Detection and Response).", type: "commentary" }
        ]
    },
    "gulistan": {
        title: "The Gulistan",
        content: [
            "THE GULISTAN",
            "(THE ROSE GARDEN)",
            { text: "Rewritten in Everyday Modern British English. Note: This version uses common British idioms and slang to help you learn how native speakers talk today.", type: "commentary" },
            "CHAPTER I: ON THE MANNERS OF KINGS",
            "STORY I",
            { text: `I once heard of a king who ordered a prisoner to be put to death. The poor bloke, having absolutely nothing left to lose, started giving the King a proper earful, swearing and slagging him off. As the saying goes: "Anyone who washes their hands of life says whatever is in their heart."\n\nThe King asked: "What's he going on about?"\n\nA Good-Hearted Minister: "My Lord, he's quoting a holy verse: 'Paradise is waiting for those who keep their temper and forgive others, for God loves a decent sort.'"\n\nThe King felt gutted for the man and decided to let him off the hook.\n\nA Rival Minister: "It's not right for people like us to tell porkies (lies) to a king. That prisoner was actually cursing you and calling you all sorts of names."\n\nThe King frowned at this rival. "I prefer that man's lie to your truth," the King said. "His lie was meant to keep the peace, but your truth was just stirring the pot. As wise men say: 'A lie that sorts things out is better than a truth that causes a ruckus.'"`, type: "story" },
            { text: "Sometimes, being brutally honest just to cause trouble is worse than telling a \"fib\" to save someone's neck. The King valued mercy over being technically correct.", type: "commentary" },
            "STORY II",
            { text: `A king named Mahmud Sabuktagin appeared in a dream a hundred years after he'd popped his clogs (died). His body had turned to dust, but his eyes were still moving in their sockets, having a gander (look) around.\n\nNone of the clever clogs (wise men) could explain it, except for a poor dervish. He bowed and said: "His eyes are still looking around because he's worried his kingdom has been taken over by some other geezer."`, type: "story" },
            { text: "This shows that power-hungry people can't let go, even after they're dead. The King was so attached to his throne he couldn't rest in peace.", type: "commentary" },
            "STORY III",
            { text: `A prince was born extremely titchy (short) and plain, while all his brothers were tall and handsome. One day, his dad looked at him like he was a bit of a disappointment.\n\nThe lad was sharp as a tack and said: "Dad, a clever dwarf is better than a daft giant. Bigger isn't always better. A sheep is clean and useful, but an elephant is just a massive lump."\n\nThe father had a chuckle, and the advisors agreed, but the brothers were green with envy. Later, in a scrap (battle), this short prince was the first to charge in, fighting like a lion while the others were bricking it (scared). He led the army to a win.\n\nThe King was chuffed to bits (very pleased) and made him his heir. The brothers were so jealous they tried to spike his food with poison. His sister saw them from a window and banged the shutters shut to warn him. The prince twigged (understood) what was happening and didn't eat. He said: "It's impossible for talented blokes to die just so useless ones can take their place."`, type: "story" },
            { text: "Size doesn't matter; brains and bottle (courage) do. Also, success breeds jealousy, even in your own family.", type: "commentary" }
        ]
    },
    "dune": {
        title: "Dune",
        content: [
          { text: "THE GOM JABBAR", type: "commentary"},
          { text: "Right then, this is the chapter's title. The Gom Jabbar is a key plot device you'll learn about shortly. It’s a test of one's humanity, a bit of a make-or-break moment.", type: "commentary"},
          { text: "A beginning is the time for taking the most fastidious care that the balances are correct. This every sister of the Bene Gesserit knows.", type: "story"},
          { text: "This sets a rather philosophical tone. It introduces the Bene Gesserit, a powerful sisterhood, and suggests that beginnings are delicate and require a great deal of care. It's hinting that what's about to happen is a bit complex.", type: "commentary"},
          { text: "To begin your study of the life of Muad’Dib, then, take care that you first place him in his time: born in the 57th year of the Padishah Emperor, Shaddam IV.", type: "story"},
          { text: "Our narrator, this Princess Irulan, is writing a history. She's introducing the main character, Paul Atreides (who'll later be known as Muad’Dib), and gives his birth year, putting him smack in a specific historical context within this fictional universe.", type: "commentary"},
          { text: "And take the most special care that you locate Muad’Dib in his place: the planet Arrakis.", type: "story"},
          { text: "This establishes the setting. Arrakis, also known as Dune, is dead central to the story and to Paul's destiny, even though he wasn't born there.", type: "commentary"},
          { text: "Do not be deceived by the fact that he was born on Caladan and lived his first fifteen years there. Arrakis, the planet known as Dune, is forever his place.", type: "story"},
          { text: "The narrator is making it dead clear that Paul's destiny is tied to the desert planet Arrakis, not his lush, water-rich homeworld of Caladan. This is a massive hint that a major life change is on the cards for him.", type: "commentary"},
          { text: "—from ‘Manual of Muad’Dib’ by the Princess Irulan", type: "story"},
          { text: "This tells us the opening bit is an excerpt from a book written by Princess Irulan. She's a historian within the story, chronicling the life of our hero, Paul/Muad’Dib.", type: "commentary"},
          { text: "In the week before their departure to Arrakis, when all the final scurrying about had reached a near unbearable frenzy, an old crone came to visit the mother of the boy, Paul.", type: "story"},
          { text: "Right, the story kicks off. Paul's family is in the middle of a chaotic move to the planet Arrakis. A mysterious and clearly important old woman rocks up to see Paul's mum, Jessica.", type: "commentary"},
          { text: "It was a warm night at Castle Caladan, and the ancient pile of stone that had served the Atreides family as home for twenty-six generations had the familiar humid feel of such places before a change in the weather.", type: "story"},
          { text: "This sets the scene on their home planet, Caladan. The mention of 26 generations shows that the Atreides family is an old and noble house, proper aristocracy. The 'humid feel' gives a sense of foreboding, as if something bad's about to happen.", type: "commentary"}
        ]
    }
};