
export const books: Record<string, { title: string; content: string[] }> = {
    "a-tale-of-two-cities": {
        title: "A Tale of Two Cities",
        content: [
            "BOOK THE FIRST: POVERTY",
            "CHAPTER 1. Sun and Shadow",
            "Thirty years ago, on a specific day, Marseilles was absolutely baking in the sun.",
            "A scorching sun on a fierce August day wasn't any rarer in southern France back then than it is now.",
            "Everything in and around Marseilles stared up at the boiling sky, and the sky stared right back, until staring became a universal habit there.",
            "Visitors felt awkward getting stared down by the blinding white houses, the white walls, the white streets, the dry stretches of road, and the hills where all the greenery had been burnt away.",
            "The only things that weren't staring intensely were the vines, drooping under the weight of their grapes. Even they winked a little now and then, whenever the hot air barely moved their leaves.",
            "There wasn't a breath of wind to cause a ripple on the dirty water in the harbour, or on the beautiful sea outside it.",
            "You could see a clear line between the two colours, black and blue, showing exactly where the clean sea stopped; it refused to mix with the filthy harbour water.",
            "Boats without covers were too hot to touch; ships blistered where they were tied up; the stone quays hadn't cooled down, day or night, for months.",
            "People from all over—Hindus, Russians, Chinese, Spaniards, Portuguese, Englishmen, Frenchmen, Genoese, Neapolitans, Venetians, Greeks, Turks—everyone who had come to trade in Marseilles sought shade.",
            "They hid anywhere they could from a sea that was too blue to look at and a purple sky that looked like it held a massive, flaming jewel of fire.",
            "The glare everywhere made your eyes ache. Looking towards the distant Italian coast, there was a bit of relief thanks to some light mist rising from the sea, but that was it.",
            "Far away, the dusty roads stared from the hillsides and hollows.",
            "Far away, the dusty vines hanging over cottages and the rows of dry trees offered no shade, drooping under the glare of the earth and sky.",
            "The horses with their drowsy bells, pulling carts slowly inland, did the same; so did the drivers lying down in the carts, mostly asleep; so did the exhausted farm workers.",
            "Everything living or growing was crushed by the glare, except for the lizards darting over stone walls, and the cicadas, chirping their dry, hot sound like a rattle.",
            "Even the dust was scorched brown, and the air shimmered as if it were panting.",
            "Blinds, shutters, curtains, and awnings were all shut tight to keep out the glare. If you left even a tiny crack, the sun shot in like a white-hot arrow.",
            "The churches were the best escape.",
            "Coming out of the dark, cool pillars and arches—dotted with flickering candles and full of ugly old shadows praying, spitting, and begging—felt like diving into a river of fire and swimming for your life to the nearest bit of shade.",
            "So, with people lounging wherever there was shade, with hardly any talking or dogs barking, just the occasional clashing of church bells and drumming, Marseilles was broiling in the sun that day.",
            "In Marseilles at that time, there was a nasty prison.",
            "In one of its cells—a place so repulsive that even the sun seemed to blink and look away, leaving it to whatever reflected light could find its way in—were two men.",
            "Besides them, the room held a battered bench stuck to the wall, a draughts board roughly carved into it with a knife, a set of draughts made from old buttons and soup bones, a set of dominoes, two mats, and two or three wine bottles.",
            "That was it, apart from the rats and other hidden vermin, and the visible vermin: the two men.",
            "The cell got its light through a large iron grate, like a window, which allowed it to be inspected from the gloomy staircase outside.",
            "There was a broad stone ledge at the bottom of this grate, three or four feet off the ground.",
            "One of the men was lolling on this ledge, half-sitting and half-lying, with his knees up and his feet and shoulders pressed against the sides of the opening.",
            "The bars were wide enough for him to stick his arm through up to the elbow, so he held on casually to make himself comfortable.",
            "The smell of prison was on everything. The trapped air, the trapped light, the trapped damp, the trapped men—everything was ruined by the confinement.",
            "Just as the men looked faded and haggard, the iron was rusty, the stone was slimy, the wood was rotten, the air felt stale, and the light was dim.",
            "Like a well, a vault, or a tomb, the prison knew nothing of the brightness outside. It would have kept its polluted atmosphere even if you moved it to a tropical island.",
            "The man lying on the window ledge actually felt chilly. He pulled his big cloak tighter with an impatient shrug and growled, 'To hell with this Brigand of a Sun that never shines in here!'",
            "He was waiting to be fed, looking sideways through the bars to see down the stairs, looking a lot like a wild beast waiting for food.",
            "But his eyes, set too close together, weren't as noble as a lion's; they were sharp rather than bright—like pointed weapons with no depth. They glittered and snapped open and shut. A clockmaker could have made a better pair.",
            "He had a hook nose, which was handsome enough, but it was too high up between his eyes, just like his eyes were too close together.",
            "He was a big, tall man with thin lips (when you could see them under his thick moustache) and messy, dry hair of no specific colour, though it had streaks of red.",
            "The hand holding the grate—covered in ugly, freshly healed scratches—was unusually small and plump; it would have been white if not for the prison dirt.",
            "The other man was lying on the stone floor, covered by a rough brown coat.",
            "'Get up, pig!' growled the first man. 'Don't sleep when I'm hungry.'",
            "'It's all the same, master,' said the 'pig', submissively but cheerfully. 'I can wake when I want, I can sleep when I want. It makes no difference.'",
            "As he said this, he got up, shook himself, scratched, tied his brown coat loosely around his neck by the sleeves (he'd been using it as a blanket), and sat on the floor yawning, leaning his back against the wall opposite the grate.",
            "'Tell me the time,' grumbled the first man.",
            "'The midday bells will ring... in forty minutes.' He paused slightly, looking around the cell as if reading the information from the walls.",
            "'You're like a clock. How do you always know?'",
            "'How can I say? I always know the time and where I am. I was brought here at night, straight off a boat, but I know where I am. Look here! Marseilles harbour,' he said, drawing a map on the floor with a dark finger.",
            "'Toulon (where the galleys are), Spain over there, Algiers over there. Moving left, Nice. Round the coast to Genoa. Genoa Mole and Harbour. Quarantine Ground. The City; terrace gardens full of bella donna flowers. Here, Porto Fino. Head out for Leghorn. Out again for Civita Vecchia, then away to—hey! There's no room for Naples,' he'd reached the wall by then, 'but it's all the same; it's in there!'",
            "He stayed on his knees, looking up at his cellmate with a lively expression for someone in prison.",
            "He was a sunburnt, quick, agile little man, though a bit stocky. He had earrings in his brown ears, white teeth that lit up his funny brown face, jet-black hair around his brown neck, and a ragged red shirt open at his chest.",
            "He wore loose sailor trousers, decent shoes, a long red cap, and a red sash around his waist with a knife tucked in it.",
            "'Just watch if I don't go back to Naples the same way I came! Look here, master! Civita Vecchia, Leghorn, Porto Fino, Genoa, the Coast, Off Nice (which is in there), Marseilles, you and me.'",
            "'The jailer's room and his keys are where my thumb is; and here at my wrist is where they keep the national razor—the guillotine.'",
            "The other man suddenly spat on the floor and made a gurgling noise in his throat.",
            "Immediately after, a lock below gurgled too, and a door banged shut. Slow footsteps started coming up the stairs; the sound of a sweet little voice mixed with the noise. The jailer appeared carrying his daughter, who was three or four years old, and a basket.",
            "'How's the world this morning, gentlemen? My little one is doing the rounds with me to peek at her father's birds. Go on then! Look at the birds, my pretty, look at the birds.'",
            "He looked sharply at the 'birds' himself as he held the child up to the grate, especially eyeing the little man, whose energy he seemed to mistrust.",
            "'I've brought your bread, Signor John Baptist,' he said (they spoke in French, but the little man was Italian). 'And if I might recommend you stop gambling—'",
            "'You don't recommend the master stop!' said John Baptist, smiling and showing his teeth.",
            "'Oh! But the master wins,' the jailer replied, giving the other man a look that wasn't particularly friendly. 'And you lose. It's totally different. You get stale bread and sour drink out of it; he gets Lyons sausage, veal in jelly, white bread, Stracchino cheese, and good wine. Look at the birds, my pretty!'",
            "'Poor birds!' said the child.",
            "Her pretty little face, full of pure compassion as she peeked shyly through the bars, looked like an angel in that prison. John Baptist stood up and moved towards her, as if drawn to her. The other 'bird' stayed where he was, just glancing impatiently at the basket.",
            "'Wait!' said the jailer, putting his daughter on the outer ledge. 'She can feed the birds.'",
            "'This big loaf is for Signor John Baptist. We have to break it to fit it through the cage. There, a tame bird to kiss your little hand!'",
            "'This sausage in a vine leaf is for Monsieur Rigaud. Again—this veal in jelly is for Monsieur Rigaud. Again—these three white rolls are for Monsieur Rigaud. Again, this cheese—again, this wine—again, this tobacco—all for Monsieur Rigaud. Lucky bird!'",
            "The child pushed all these things through the bars into the soft, smooth hand with clear fear—pulling her own hand back more than once and looking at the man with a mix of fright and anger.",
            "However, she handed the lump of coarse bread to the dark, rough, knotted hands of John Baptist (who had fewer fingernails on all his fingers combined than Monsieur Rigaud had on one) with total confidence; and when he kissed her hand, she stroked his face affectionately.",
            "Monsieur Rigaud, not caring about this, kept the father happy by laughing and nodding at the girl whenever she gave him something. As soon as he had his food arranged on the ledge, he started eating with gusto.",
            "When Monsieur Rigaud laughed, his face changed in a way that was striking but not nice. His moustache went up under his nose, and his nose came down over his moustache, making him look sinister and cruel.",
            "'There!' said the jailer, tipping his basket upside down to empty the crumbs. 'I've spent all the money I was given; here's the receipt, job done. Monsieur Rigaud, as I expected yesterday, the President wants the pleasure of your company an hour after midday today.'",
            "'To try me, eh?' said Rigaud, pausing with his knife in hand and food in his mouth.",
            "'You said it. To put you on trial.'",
            "'No news for me?' asked John Baptist, who had started munching his bread contentedly.",
            "The jailer shrugged.",
            "'My Lady! Am I going to rot here all my life, father?'",
            "'What do I know!' cried the jailer, turning on him with southern intensity, waving his hands as if threatening to tear him apart. 'My friend, how can I possibly tell how long you'll be here? What do I know, John Baptist Cavalletto? For the life of me! There are prisoners here sometimes who aren't in such a devil of a rush to be tried.'",
            "He seemed to glance sideways at Monsieur Rigaud with this remark; but Rigaud had gone back to his meal, though perhaps eating a bit slower than before.",
            "'Goodbye, my birds!' said the jailer, picking up his pretty child and prompting her to say it with a kiss.",
            "'Goodbye, my birds!' the child repeated.",
            "Her innocent face looked back so brightly over his shoulder as he walked away, singing her a nursery rhyme:\n\n'Who passes by this road so late?\nCompagnon de la Majolaine!\nWho passes by this road so late?\nAlways gay!'",
            "John Baptist felt honour-bound to reply through the grate, in time and tune, though his voice was a bit rough:\n\n'Of all the king's knights 'tis the flower,\nCompagnon de la Majolaine!\nOf all the king's knights 'tis the flower,\nAlways gay!'",
            "This duet followed them down the steep stairs so far that the jailer had to stop to let his daughter hear the end of the song and repeat the chorus while they were still visible. Then they disappeared, but the little voice kept singing until the door slammed shut.",
            "Monsieur Rigaud, finding John Baptist standing in his way before the echoes died out (even echoes were weak in prison), nudged him with his foot to remind him to get back to his dark corner.",
            "The little man sat down again on the floor with the ease of someone used to sitting on pavements. He lined up three chunks of coarse bread and, starting on a fourth, began eating them as if clearing them away was a game.",
            "He might have glanced at the Lyons sausage or the veal in jelly, but they didn't last long enough to make his mouth water; Monsieur Rigaud finished them off quickly, despite the looming trial, and sucked his fingers clean, wiping them on the vine leaves.",
            "Then, pausing his drinking to look at his cellmate, his moustache went up and his nose came down.",
            "'How's the bread?'",
            "'A bit dry, but I've got my old sauce here,' replied John Baptist, holding up his knife.",
            "'What sauce?'",
            "'I can cut my bread like this—like a melon. Or like this—like an omelette. Or like this—like a fried fish. Or like this—like Lyons sausage,' said John Baptist, acting out the cuts on his bread and chewing soberly.",
            "'Here!' cried Monsieur Rigaud. 'Have a drink. You can finish this.'",
            "It wasn't a huge gift, as there was hardly any wine left; but Signor Cavalletto jumped up, took the bottle gratefully, tipped it up, and smacked his lips.",
            "'Put the bottle with the others,' said Rigaud.",
            "The little man obeyed and stood ready to give him a light; Rigaud was rolling a cigarette using little squares of paper that came with the tobacco.",
            "'Here! You can have one.'",
            "'A thousand thanks, master!' John Baptist said in Italian, with the quick, polite manner of his people.",
            "Monsieur Rigaud stood up, lit a cigarette, put the rest in his pocket, and stretched out on the bench. Cavalletto sat on the floor, holding his ankles, smoking peacefully.",
            "Monsieur Rigaud's eyes seemed uncomfortably drawn to the spot on the floor where John Baptist had put his thumb on the imaginary map earlier. He looked there so often that the Italian noticed and looked back and forth in surprise.",
            "'What a hellhole this is!' said Monsieur Rigaud, breaking the silence. 'Look at the daylight. Day? It looks like last week's light, or light from six months ago—six years ago. So weak and dead!'",
            "The light drifted down a square shaft that blocked a window on the stairs, so you could never see the sky—or anything else.",
            "'Cavalletto,' said Monsieur Rigaud, suddenly looking away from the shaft they were both staring at, 'you know I'm a gentleman, right?'",
            "'Definitely, definitely!'",
            "'How long have we been here?'",
            "'Me, eleven weeks at midnight tomorrow. You, nine weeks and three days at five this afternoon.'",
            "'Have I ever done anything here? Ever touched the broom, spread the mats, rolled them up, found the draughts pieces, collected the dominoes, or done any work at all?'",
            "'Never!'",
            "'Have you ever expected me to do any work?'",
            "John Baptist answered with that specific shake of the right forefinger that means a strong 'no' in Italian.",
            "'No! You knew from the moment you saw me that I was a gentleman?'",
            "'Altro!' replied John Baptist, closing his eyes and tossing his head. This word, which can mean yes, no, maybe, a joke, or a hundred other things depending on the tone, in this context meant a very strong 'I believe you!' or 'Too right!'",
            "'Haha! You're right! I am a gentleman! And I'll live like a gentleman and die like a gentleman! It's my plan to be a gentleman. That's my game. I'll play it out wherever I go!'",
            "He sat up, shouting triumphantly: 'Here I am! Look at me! Thrown by destiny into a cell with a mere smuggler; locked up with a poor little illegal trader whose papers are wrong, and who the police grabbed for lending his boat to other people whose papers were wrong. And yet, he instinctively recognises my status, even in this dark place. Well done! By Heaven! I win, no matter how the game goes.'",
            "Again, his moustache went up and his nose came down.",
            "'What time is it now?' he asked, looking pale and sweaty in a way that didn't match his laughter.",
            "'Just past half-twelve.'",
            "'Good! The President will have a gentleman in front of him soon. Come on! Shall I tell you what I'm accused of? It's now or never, because I won't be coming back here. Either I walk free, or I go to get ready for a shave. You know where they keep the razor.'",
            "Signor Cavalletto took the cigarette out of his mouth and looked more worried than you'd expect.",
            "'I am a'—Monsieur Rigaud stood up to say it—'I am a cosmopolitan gentleman. I don't belong to any specific country. My father was Swiss. My mother was French by blood, English by birth. I was born in Belgium. I'm a citizen of the world.'",
            "His dramatic pose, with one hand on his hip inside his cloak, and the way he spoke to the wall instead of his cellmate, suggested he was rehearsing for the President rather than just talking to little John Baptist Cavalletto.",
            "'Let's say I'm thirty-five. I've seen the world. I've lived here, there, everywhere—and always like a gentleman. I've been treated and respected as a gentleman everywhere. If you try to make me look bad by saying I've lived by my wits—well, how do your lawyers live? Your politicians? Your schemers? Your stockbrokers?'",
            "He kept waving his small, smooth hand around, as if it was proof of his high status.",
            "'Two years ago I came to Marseilles. I admit I was poor; I'd been ill. When your lawyers, politicians, and stockbrokers get ill and haven't saved money, they get poor too. I stayed at the Cross of Gold hotel—run by Monsieur Henri Barronneau—who was sixty-five and failing in health. I'd lived there about four months when Monsieur Barronneau had the misfortune to die. Not exactly a rare misfortune, that. It happens often enough without my help.'",
            "John Baptist had smoked his cigarette down to his fingertips, so Monsieur Rigaud generously threw him another one. He lit the second one from the ash of the first and kept smoking, looking sideways at Rigaud, who was too focused on his own story to notice.",
            "'Monsieur Barronneau left a widow. She was twenty-two. She had a reputation for being beautiful, and (which is often a different thing) actually was beautiful. I stayed at the Cross of Gold. I married Madame Barronneau. It's not for me to say if there was a big difference in class. Here I stand, covered in prison filth; but you might think I was a better match for her than her first husband.'",
            "He had a certain air of being a handsome man—which he wasn't; and a certain air of being a well-bred man—which he wasn't. It was just swagger and attitude; but in this world, confident bluffing often passes for proof.",
            "'Anyway, Madame Barronneau approved of me. That shouldn't work against me, I hope?'",
            "His eye fell on John Baptist, who quickly shook his head 'no' and whispered altro, altro, altro a bunch of times.",
            "'Now came the problems. I am proud. I'm not saying pride is good, but I am proud. It's also in my nature to be in charge. I can't submit; I have to lead. Unfortunately, Madame Rigaud's property was legally hers alone. That was her late husband's insane idea. Even more unfortunately, she had relatives.'",
            "'When a wife's relatives get involved against a husband who is a gentleman, proud, and needs to be in charge, there's no peace. There was another issue. Madame Rigaud was, unfortunately, a bit common. I tried to improve her manners and class; she (backed up by her relatives) resented my efforts.'",
            "'We started arguing; and thanks to her relatives gossiping, the neighbours found out. People said I treated Madame Rigaud cruelly. I might have been seen slapping her face—nothing more. I have a light hand; if I corrected her like that, I did it almost playfully.'",
            "If Monsieur Rigaud's smile at this point was 'playful,' Madame Rigaud's relatives would probably have preferred him to be serious.",
            "'I am sensitive and brave. I don't say it's a merit, but it's who I am. If her male relatives had confronted me openly, I'd have dealt with them. They knew that, so they plotted in secret; consequently, Madame Rigaud and I clashed often.'",
            "'Even when I wanted a little money for personal expenses, I couldn't get it without a fight—and I'm a man who needs to be in charge! One night, Madame Rigaud and I were walking amicably—I might say like lovers—on a cliff overlooking the sea. Bad luck made Madame Rigaud bring up her relatives.'",
            "'I reasoned with her, pointing out her lack of loyalty in letting them turn her against her husband. She argued back; I argued back; she got angry; I got angry and provoked her. I admit it. Frankness is part of my character.'",
            "'Finally, in a fit of rage that I will always regret, Madame Rigaud threw herself at me screaming (no doubt people heard it far away), tore my clothes, tore my hair, scratched my hands, stomped on the ground, and finally leaped over the edge, dashing herself to death on the rocks below. That is the series of events that malice has twisted into me trying to force her to give up her rights, and when she refused, struggling with her—and assassinating her!'",
            "He stepped over to the ledge, picked up some vine leaves, and wiped his hands on them, with his back to the light.",
            "'Well,' he demanded after a silence, 'have you got nothing to say to that?'",
            "'It's ugly,' replied the little man, who had stood up and was sharpening his knife on his shoe, leaning against the wall.",
            "'What do you mean?' John Baptist polished his knife silently.",
            "'Do you mean I haven't told the story correctly?'",
            "'Al-tro!' said John Baptist. The word was an apology now, meaning 'Oh, definitely not!'",
            "'What then?'",
            "'Presidents and courts are so prejudiced.'",
            "'Well,' cried the other, nervously throwing his cloak over his shoulder with a curse, 'let them do their worst!'",
            "'I think they probably will,' murmured John Baptist to himself, tucking his knife into his sash.",
            "They didn't say anything else, though they both started pacing back and forth, crossing paths every time. Monsieur Rigaud sometimes stopped, as if to explain things differently or complain angrily; but since Signor Cavalletto kept jogging along looking at the floor, nothing came of it.",
            "Eventually, the sound of a key in the lock stopped them both. Voices followed, then footsteps. The door banged, and the jailer came slowly up the stairs, followed by a guard of soldiers.",
            "'Now, Monsieur Rigaud,' he said, pausing at the grate with his keys, 'please come out.'",
            "'I'm leaving in style, I see?'",
            "'Well, unless you did,' replied the jailer, 'you might leave in so many pieces we couldn't put you back together. There's a mob, Monsieur Rigaud, and they don't love you.'",
            "He unlocked a low door in the corner of the cell. 'Now,' he said, opening it, 'come out.'",
            "Monsieur Rigaud's face went a shade of white that doesn't exist anywhere else in nature. And no human expression looks quite like the one where you can see a terrified heart beating in every line of the face. People compare it to death, but the difference is huge—it's the difference between a struggle that's over and a fight at its most desperate moment.",
            "He lit another paper cigar from his companion's, clenched it in his teeth, pulled his hat down, threw his cloak over his shoulder, and walked out onto the gallery without looking at Signor Cavalletto again. As for the little man, he was focused entirely on getting near the door to look out. Just like a beast eyeing the freedom outside its cage, he spent those few seconds peering out until the door shut.",
            "There was an officer in charge of the soldiers; a stout, capable, very calm man with a drawn sword, smoking a cigar. He briefly ordered Monsieur Rigaud into the middle of the group, stood at the front with total indifference, said 'March!', and they all went clattering down the stairs. The door slammed—the key turned—and a ray of unusual light and fresh air seemed to vanish from the jail like a wisp of cigar smoke.",
            "Left alone, the prisoner jumped onto the ledge like a monkey or a small bear to catch the last glimpse of them leaving. As he held the grate, a roar of noise reached him: yells, screams, curses, threats—all mixed together into a raging storm of sound.",
            "Anxious to know more, he leaped down, ran around the cell, leaped back up, shook the grate, leaped down again, and didn't rest until the noise faded into the distance. How many better prisoners have worn themselves out like this, with no one thinking of them? Even great kings and governors who locked them up, riding happily in the sun with people cheering them on.",
            "At last, John Baptist lay down on the bench with his face on his crossed arms and fell asleep. In his obedience, his lightness, his good humour, his short-lived anger, his acceptance of hard bread and stone floors, and his ability to sleep anywhere, he was a true son of his country.",
            "The staring sun finally finished for the day; it went down in a red, green, and golden glory. The stars came out, and fireflies mimicked them in the air below. The long dusty roads and empty plains went quiet—and the sea was so hushed it barely whispered of the time when it shall give up its dead."
        ]
    },
    "dune": {
        title: "Dune",
        content: [
            "THE GOM JABBAR",
            "A beginning is the time when you have to be absolutely finicky about getting the balances right. Every sister of the Bene Gesserit knows this.",
            "So, to start your study of the life of Muad’Dib, make sure you first place him in his proper time: born in the 57th year of the Padishah Emperor, Shaddam IV.",
            "And you must take special care to place Muad’Dib in his proper place: the planet Arrakis.",
            "Don’t be fooled by the fact that he was born on Caladan and lived his first fifteen years there. Arrakis, the planet known as Dune, is his true home. Forever.",
            "—from ‘Manual of Muad’Dib’ by the Princess Irulan",
            "In the week before they were set to leave for Arrakis, when the final rush had turned into absolute bedlam, an old crone came to visit the mother of the boy, Paul.",
            "It was a warm night at Castle Caladan. The ancient pile of stone, which had served the Atreides family as a home for twenty-six generations, had that clammy, \"sweating-wall\" feeling you get before the weather turns.",
            "The old woman was let in by the side door, down the vaulted passage by Paul’s room. She was allowed a moment to peek in at him while he lay in bed.",
            "By the dim light of a suspensor lamp hanging near the floor, the awakened boy could see a bulky female shape at his door, standing one step ahead of his mother.",
            "The old woman was like a witch from a storybook—hair like matted spiderwebs, a hood hiding her dark features, and eyes like glittering jewels.",
            "\"Isn't he a bit small for his age, Jessica?\" the old woman asked. Her voice wheezed and twanged like an untuned guitar.",
            "Paul’s mother answered in her soft, deep voice: \"The Atreides are known to start growing late, Your Reverence.\"",
            "\"So I’ve heard, so I’ve heard,\" wheezed the old woman. \"Yet he’s already fifteen.\"",
            "\"Yes, Your Reverence.\"",
            "\"He’s awake and listening to us,\" said the old woman. \"Sly little rascal.\" She chuckled. \"But royalty needs to be sly. And if he really is the Kwisatz Haderach... well...\"",
            "In the shadows of his bed, Paul narrowed his eyes to slits. Two bird-bright ovals—the eyes of the old woman—seemed to expand and glow as they stared right into his.",
            "\"Sleep well, you sly little rascal,\" said the old woman. \"Tomorrow you’ll need all your wits about you to meet my gom jabbar.\"",
            "And with that, she was gone, shoving his mother out and closing the door with a solid thump.",
            "Paul lay awake wondering: What on earth is a gom jabbar?",
            "In all the chaos during this move, the old woman was the strangest thing he had seen.",
            "Your Reverence.",
            "And the way she called his mother \"Jessica\" like she was a common serving girl, instead of what she actually was—a Bene Gesserit Lady, a duke’s partner, and mother of the heir.",
            "Is a gom jabbar something from Arrakis I need to know about before we go? he wondered.",
            "He mouthed her strange words: Gom jabbar... Kwisatz Haderach.",
            "There had been so much to learn. Arrakis would be so different from Caladan that Paul’s mind was spinning with the new information.",
            "Arrakis—Dune—Desert Planet.",
            "Thufir Hawat, his father’s Master of Assassins, had explained it all: their mortal enemies, the Harkonnens, had been on Arrakis for eighty years. They held the planet as a sort of semi-fiefdom under a CHOAM Company contract to mine the geriatric spice, melange.",
            "Now the Harkonnens were leaving to be replaced by the House of Atreides in a complete fiefdom—an apparent victory for Duke Leto.",
            "Yet, Hawat had said, this \"victory\" was actually incredibly dangerous, because Duke Leto was popular among the Great Houses of the Landsraad.",
            "\"A popular man makes powerful people jealous,\" Hawat had said.",
            "Arrakis—Dune—Desert Planet.",
            "Paul fell asleep and dreamed of a cavern on Arrakis. There were silent people all around him moving in the dim light of glowglobes.",
            "It was solemn there, like a cathedral, and he listened to a faint sound—the drip-drip-drip of water. Even while he was still dreaming, Paul knew he would remember it when he woke up. He always remembered the dreams that predicted the future.",
            "The dream faded.",
            "Paul half-woke to feel the warmth of his bed—thinking... thinking.",
            "This world of Castle Caladan, without any mates his own age to play with, perhaps didn't deserve a sad farewell.",
            "Dr. Yueh, his teacher, had hinted that the class system wasn't so rigid on Arrakis. The planet sheltered people who lived at the desert edge without any commanders or lords to boss them about: \"will-o’-the-sand\" people called Fremen, who weren't listed on any Imperial census.",
            "Arrakis—Dune—Desert Planet.",
            "Paul sensed his own stress and decided to practice one of the mind-body lessons his mother had taught him.",
            "Three quick breaths triggered the response.",
            "He fell into the floating awareness... focusing his consciousness... dilating the aorta... avoiding the unfocused autopilot of the mind... choosing to be conscious...",
            "Blood enriched and flooding the overload regions... you don't get food-safety-freedom by instinct alone... animal consciousness doesn't look beyond the current moment or understand that its species could go extinct...",
            "The animal destroys and does not produce... animal pleasures stay close to simple sensation and avoid deep perception... the human requires a background grid to see his universe... focused consciousness forms your grid...",
            "Bodily integrity follows nerve-blood flow according to the deepest awareness of cell needs... all things/cells/beings are temporary... strive for flow-permanence within...",
            "Over and over and over, the lesson rolled through Paul’s floating awareness.",
            "When dawn touched Paul’s windowsill with yellow light, he sensed it through closed eyelids. He opened them, hearing the renewed hustle and bustle in the castle, seeing the familiar patterned beams of his bedroom ceiling.",
            "The hall door opened and his mother peered in. Her hair was like shaded bronze held with a black ribbon at the crown, her oval face emotionless, her green eyes staring solemnly.",
            "\"You’re awake,\" she said. \"Did you sleep well?\"",
            "\"Yes.\"",
            "He studied how tall she was, saw the hint of tension in her shoulders as she chose clothes for him from the closet racks. Anyone else might have missed the tension, but she had trained him in the Bene Gesserit Way—in the tiny details of observation.",
            "She turned, holding a semi-formal jacket for him. It carried the red Atreides hawk crest above the breast pocket.",
            "\"Hurry and get dressed,\" she said. \"Reverend Mother is waiting.\"",
            "\"I dreamed of her once,\" Paul said. \"Who is she?\"",
            "\"She was my teacher at the Bene Gesserit school. Now, she’s the Emperor’s Truthsayer. And Paul...\" She hesitated. \"You must tell her about your dreams.\"",
            "\"I will. Is she the reason we got Arrakis?\"",
            "\"We did not get Arrakis.\" Jessica flicked dust from a pair of trousers and hung them with the jacket on the stand beside his bed. \"Don’t keep Reverend Mother waiting.\"",
            "Paul sat up and hugged his knees. \"What’s a gom jabbar?\"",
            "Again, the training she had given him exposed her almost invisible hesitation, a nervous slip he felt as fear.",
            "Jessica walked to the window, threw the curtains wide, and stared across the river orchards toward Mount Syubi.",
            "\"You’ll learn about... the gom jabbar soon enough,\" she said.",
            "He heard the fear in her voice and wondered why.",
            "Jessica spoke without turning. \"Reverend Mother is waiting in my morning room. Please hurry.\"",
            "The Reverend Mother Gaius Helen Mohiam sat in a tapestried chair watching mother and son approach.",
            "Windows on each side of her overlooked the curving southern bend of the river and the green farmlands of the Atreides estate, but the Reverend Mother ignored the view.",
            "She was feeling her age this morning, and was more than a little cranky. She blamed it on space travel and associating with that abominable Spacing Guild and its secretive ways.",
            "But here was a mission that required personal attention from a Bene Gesserit-with-the-Sight. Even the Padishah Emperor’s Truthsayer couldn’t dodge that responsibility when duty called.",
            "Damn that Jessica! the Reverend Mother thought. If only she’d borne us a girl as she was ordered to do!",
            "Jessica stopped three paces from the chair and dropped a small curtsy, a gentle flick of her left hand along the line of her skirt.",
            "Paul gave the short bow his dancing master had taught him—the one used \"when in doubt of another’s rank.\"",
            "The nuances of Paul’s greeting were not lost on the Reverend Mother. She said: \"He’s a cautious one, Jessica.\"",
            "Jessica’s hand went to Paul’s shoulder and tightened there. For a heartbeat, fear pulsed through her palm. Then she got herself under control.",
            "\"Thus he has been taught, Your Reverence.\"",
            "What is she afraid of? Paul wondered.",
            "The old woman studied Paul in one quick glance: face oval like Jessica’s, but strong bones... hair: the Duke’s jet-black but with the brow-line of the maternal grandfather who cannot be named, and that thin, disdainful nose; shape of directly staring green eyes: like the old Duke, the paternal grandfather who is dead.",
            "Now, there was a man who appreciated the power of showing off—even in death, the Reverend Mother thought.",
            "\"Teaching is one thing,\" she said, \"the basic ingredient is another. We shall see.\" The old eyes darted a hard look at Jessica. \"Leave us. I order you to practice the meditation of peace.\"",
            "Jessica took her hand from Paul’s shoulder. \"Your Reverence, I—\"",
            "\"Jessica, you know it must be done.\"",
            "Paul looked up at his mother, puzzled.",
            "Jessica straightened up. \"Yes... of course.\"",
            "Paul looked back at the Reverend Mother. Politeness and his mother’s obvious awe of this old woman argued for caution. Yet he felt an angry worry at the fear he sensed radiating from his mother.",
            "\"Paul...\" Jessica took a deep breath. \"... this test you’re about to receive... it’s important to me.\"",
            "\"Test?\" He looked up at her.",
            "\"Remember that you’re a duke’s son,\" Jessica said. She spun around and strode from the room with a dry swishing of her skirt. The door closed solidly behind her.",
            "Paul faced the old woman, keeping his anger in check. \"Does one dismiss the Lady Jessica as though she were a serving girl?\"",
            "A smile flicked the corners of the wrinkled old mouth. \"The Lady Jessica was my serving girl, lad, for fourteen years at school.\" She nodded. \"And a good one, too. Now, you come here!\"",
            "The command whipped out at him. Paul found himself obeying before he could think about it.",
            "Using the Voice on me, he thought. He stopped at her gesture, standing beside her knees.",
            "\"See this?\" she asked.",
            "From the folds of her gown, she lifted a green metal cube about fifteen centimetres on one side. She turned it and Paul saw that one side was open—black and oddly frightening. No light penetrated that open blackness.",
            "\"Put your right hand in the box,\" she said.",
            "Fear shot through Paul. He started to back away, but the old woman said: \"Is this how you obey your mother?\"",
            "He looked up into those bird-bright eyes.",
            "Slowly, feeling the compulsion and unable to stop it, Paul put his hand into the box. He felt a sense of cold first as the blackness closed around his hand, then slick metal against his fingers and a prickling sensation, as though his hand were asleep.",
            "A predatory look filled the old woman’s face. She lifted her right hand away from the box and poised it close to the side of Paul’s neck. He saw a glint of metal there and started to turn toward it.",
            "\"Stop!\" she snapped.",
            "Using the Voice again! He swung his attention back to her face.",
            "\"I hold at your neck the gom jabbar,\" she said. \"The gom jabbar, the high-handed enemy. It’s a needle with a drop of poison on its tip. Ah-ah! Don’t pull away or you’ll feel that poison.\"",
            "Paul tried to swallow, but his throat was dry. He couldn't take his eyes off the wrinkled old face, the glistening eyes, the pale gums around silvery metal teeth that flashed as she spoke.",
            "\"A duke’s son must know about poisons,\" she said. \"It’s the way of our times, eh? Musky, to be poisoned in your drink. Aumas, to be poisoned in your food. The quick ones and the slow ones and the ones in between. Here’s a new one for you: the gom jabbar. It kills only animals.\"",
            "Pride overcame Paul’s fear. \"You dare suggest a duke’s son is an animal?\" he demanded.",
            "\"Let us say I suggest you may be human,\" she said. \"Steady! I warn you not to try jerking away. I am old, but my hand can drive this needle into your neck before you escape me.\"",
            "\"Who are you?\" he whispered. \"How did you trick my mother into leaving me alone with you? Are you from the Harkonnens?\"",
            "\"The Harkonnens? Bless us, no! Now, be silent.\" A dry finger touched his neck and he stilled the involuntary urge to leap away.",
            "\"Good,\" she said. \"You pass the first test. Now, here’s how the rest of it works: If you take your hand out of the box, you die. That is the only rule. Keep your hand in the box and live. Take it out and die.\"",
            "Paul took a deep breath to stop his trembling. \"If I call out, there’ll be servants on you in seconds and you’ll die.\"",
            "\"Servants will not pass your mother who stands guard outside that door. Depend on it. Your mother survived this test. Now it’s your turn. Be honoured. We seldom administer this to boys.\"",
            "Curiosity reduced Paul’s fear to a manageable level. He heard truth in the old woman’s voice; there was no denying it. If his mother stood guard out there... if this were truly a test...",
            "And whatever it was, he knew he was caught in it, trapped by that hand at his neck: the gom jabbar. He recalled the response from the Litany against Fear as his mother had taught him from the Bene Gesserit rite.",
            "I must not fear. Fear is the mind-killer. Fear is the little-death that brings total obliteration. I will face my fear. I will permit it to pass over me and through me. And when it has gone past I will turn the inner eye to see its path. Where the fear has gone there will be nothing. Only I will remain.",
            "He felt calmness return, and said: \"Get on with it, old woman.\"",
            "\"Old woman!\" she snapped. \"You’ve got guts, I'll give you that. Well, we shall see, sirra.\"",
            "She bent close, lowering her voice almost to a whisper. \"You will feel pain in this hand within the box. Pain. But! Withdraw the hand and I’ll touch your neck with my gom jabbar—the death so swift it’s like the fall of the headsman’s axe. Withdraw your hand and the gom jabbar takes you. Understand?\"",
            "\"What’s in the box?\"",
            "\"Pain.\"",
            "He felt increased tingling in his hand and pressed his lips tightly together. How could this be a test? he wondered. The tingling became an itch.",
            "The old woman said: \"You’ve heard of animals chewing off a leg to escape a trap? That’s an animal kind of trick. A human would remain in the trap, endure the pain, feigning death so that he might kill the trapper and remove a threat to his kind.\"",
            "The itch became the faintest burning. \"Why are you doing this?\" he demanded.",
            "\"To determine if you’re human. Be silent.\"",
            "Paul clenched his left hand into a fist as the burning sensation increased in the other hand. It mounted slowly: heat upon heat upon heat... upon heat.",
            "He felt the fingernails of his free hand biting into his palm. He tried to flex the fingers of the burning hand, but couldn't move them.",
            "\"It burns,\" he whispered.",
            "\"Silence!\"",
            "Pain throbbed up his arm. Sweat stood out on his forehead. Every fibre of his body cried out to yank the hand from the burning pit... but... the gom jabbar.",
            "Without turning his head, he tried to move his eyes to see that terrible needle poised beside his neck. He sensed that he was breathing in gasps, tried to slow his breaths and couldn't.",
            "Pain!",
            "His world emptied of everything except that hand immersed in agony, and the ancient face inches away staring at him.",
            "His lips were so dry he had a difficulty separating them.",
            "The burning! The burning!",
            "He thought he could feel skin curling black on that agonised hand, the flesh crisping and dropping away until only charred bones remained.",
            "It stopped!",
            "As though a switch had been turned off, the pain stopped.",
            "Paul felt his right arm trembling, felt sweat bathing his body.",
            "\"Enough,\" the old woman muttered. \"Kull wahad! No woman child ever withstood that much. I must’ve wanted you to fail.\"",
            "She leaned back, taking the gom jabbar away from his neck. \"Take your hand from the box, young human, and look at it.\"",
            "He fought down an aching shiver, staring at the lightless void where his hand seemed to stay of its own free will. Memory of pain stopped every movement. Reason told him he would pull out a blackened stump from that box.",
            "\"Do it!\" she snapped.",
            "He jerked his hand from the box and stared at it, astonished.",
            "Not a mark. No sign of agony on the flesh. He held up the hand, turned it, flexed the fingers.",
            "\"Pain by nerve induction,\" she said. \"Can’t go around maiming potential humans. There are those who’d give a pretty penny for the secret of this box, though.\" She slipped it into the folds of her gown.",
            "\"But the pain—\" he said.",
            "\"Pain,\" she sniffed. \"A human can override any nerve in the body.\"",
            "Paul felt his left hand aching, uncurled the clenched fingers, and looked at four bloody marks where his fingernails had bitten his palm. He dropped the hand to his side and looked at the old woman.",
            "\"You did that to my mother once?\"",
            "\"Ever sift sand through a screen?\" she asked.",
            "The sideways slash of her question shocked his mind into a higher awareness: Sand through a screen. He nodded.",
            "\"We Bene Gesserit sift people to find the humans.\"",
            "He lifted his right hand, willing the memory of the pain to return. \"And that’s all there is to it—pain?\"",
            "\"I observed you in pain, lad. Pain’s merely the axis of the test. Your mother’s told you about our ways of observing. I see the signs of her teaching in you. Our test is crisis and observation.\"",
            "He heard the confirmation in her voice, said: \"It’s the truth!\"",
            "She stared at him. He senses truth! Could he be the one? Could he truly be the one? She extinguished the excitement, reminding herself: Hope clouds observation.",
            "\"You know when people believe what they say,\" she said.",
            "\"I know it.\"",
            "The harmonics of ability confirmed by repeated testing were in his voice. She heard them and said: \"Perhaps you are the Kwisatz Haderach. Sit down, little brother, here at my feet.\"",
            "\"I prefer to stand.\"",
            "\"Your mother sat at my feet once.\"",
            "\"I’m not my mother.\"",
            "\"You hate us a little, eh?\" She looked toward the door and called out: \"Jessica!\"",
            "The door flew open and Jessica stood there staring hard-eyed into the room. The hardness melted from her as she saw Paul. She managed a faint smile.",
            "\"Jessica, have you ever stopped hating me?\" the old woman asked.",
            "\"I both love and hate you,\" Jessica said. \"The hate—that’s from pains I must never forget. The love—that’s...\"",
            "\"Just the basic fact,\" the old woman said, but her voice was gentle. \"You may come in now, but remain silent. Close the door and make sure no one interrupts us.\"",
            "Jessica stepped into the room, closed the door and stood with her back to it. My son lives, she thought. My son lives and is... human. I knew he was... but... he lives. Now, I can go on living.",
            "The door felt hard and real against her back. Everything in the room felt immediate and pressing against her senses.",
            "My son lives.",
            "Paul looked at his mother. She told the truth. He wanted to get away alone and think this experience through, but knew he could not leave until he was dismissed. The old woman had gained a power over him. They spoke the truth. His mother had undergone this test.",
            "There must be a terrible purpose in it... the pain and fear had been terrible. He understood terrible purposes. They drove against all odds. They were their own necessity. Paul felt that he had been infected with terrible purpose. He did not know yet what the terrible purpose was.",
            "\"Some day, lad,\" the old woman said, \"you, too, may have to stand outside a door like that. It takes a bit of doing.\"",
            "Paul looked down at the hand that had known pain, then up to the Reverend Mother. The sound of her voice had contained a difference then from any other voice in his experience. The words were outlined in brilliance. There was an edge to them. He felt that any question he might ask her would bring an answer that could lift him out of his flesh-world into something greater.",
            "\"Why do you test for humans?\" he asked.",
            "\"To set you free.\"",
            "\"Free?\"",
            "\"Once, men turned their thinking over to machines in the hope that this would set them free. But that only permitted other men with machines to enslave them.\"",
            "\"'Thou shalt not make a machine in the likeness of a man’s mind,'\" Paul quoted.",
            "\"Right out of the Butlerian Jihad and the Orange Catholic Bible,\" she said. \"But what the O.C. Bible should’ve said is: 'Thou shalt not make a machine to counterfeit a human mind.' Have you studied the Mentat in your service?\"",
            "\"I’ve studied with Thufir Hawat.\"",
            "\"The Great Revolt took away a crutch,\" she said. \"It forced human minds to develop. Schools were started to train human talents.\"",
            "\"Bene Gesserit schools?\"",
            "She nodded. \"We have two chief survivors of those ancient schools: the Bene Gesserit and the Spacing Guild. The Guild, so we think, emphasises almost pure mathematics. Bene Gesserit performs another function.\"",
            "\"Politics,\" he said.",
            "\"Kull wahad!\" the old woman said. She sent a hard glance at Jessica.",
            "\"I’ve not told him, Your Reverence,\" Jessica said.",
            "The Reverend Mother returned her attention to Paul. \"You worked that out on remarkably few clues,\" she said. \"Politics indeed. The original Bene Gesserit school was directed by those who saw the need of a thread of continuity in human affairs. They saw there could be no such continuity without separating human stock from animal stock—for breeding purposes.\"",
            "The old woman’s words abruptly lost their special sharpness for Paul. He felt an offence against what his mother called his instinct for rightness. It wasn’t that the Reverend Mother lied to him. She obviously believed what she said. It was something deeper, something tied to his terrible purpose.",
            "He said: \"But my mother tells me many Bene Gesserit of the schools don’t know their ancestry.\"",
            "\"The genetic lines are always in our records,\" she said. \"Your mother knows that either she’s of Bene Gesserit descent or her stock was acceptable in itself.\"",
            "\"Then why couldn’t she know who her parents are?\"",
            "\"Some do... Many don’t. We might, for example, have wanted to breed her to a close relative to set up a dominant in some genetic trait. We have many reasons.\"",
            "Again, Paul felt the offence against rightness. He said: \"You take a lot on yourselves.\"",
            "The Reverend Mother stared at him, wondering: Did I hear criticism in his voice? \"We carry a heavy burden,\" she said.",
            "Paul felt himself coming more and more out of the shock of the test. He levelled a measuring stare at her, said: \"You say maybe I’m the... Kwisatz Haderach. What’s that, a human gom jabbar?\"",
            "\"Paul,\" Jessica said. \"You mustn’t take that tone with—\"",
            "\"I’ll handle this, Jessica,\" the old woman said. \"Now, lad, do you know about the Truthsayer drug?\"",
            "\"You take it to improve your ability to detect falsehood,\" he said. \"My mother’s told me.\"",
            "\"Have you ever seen a truthtrance?\"",
            "He shook his head. \"No.\"",
            "\"The drug’s dangerous,\" she said, \"but it gives insight. When a Truthsayer’s gifted by the drug, she can look many places in her memory—in her body’s memory. We look down so many avenues of the past... but only feminine avenues.\"",
            "Her voice took on a note of sadness. \"Yet, there’s a place where no Truthsayer can see. We are repelled by it, terrorised. It is said a man will come one day and find in the gift of the drug his inward eye. He will look where we cannot—into both feminine and masculine pasts.\"",
            "\"Your Kwisatz Haderach?\"",
            "CHAPTER 2",
            "Trying to understand Muad’Dib without understanding his mortal enemies, the Harkonnens, is like trying to see the Truth without knowing what a Lie is.",
            "It is the attempt to see the Light without knowing the Darkness. It just can't be done.",
            "—from ‘Manual of Muad’Dib’ by the Princess Irulan",
            "It was a 3D relief globe of a world, partly in shadow, spinning because a fat hand covered in rings had just given it a shove.",
            "The globe sat on a stylish stand against one wall of a windowless room. The other walls were covered in a patchwork of multi-coloured scrolls, filmbooks, tapes, and reels. Light glowed in the room from golden balls hanging in floating suspension fields.",
            "An oval desk made of jade-pink petrified wood stood in the centre of the room. Floating chairs ringed it; two of them were occupied.",
            "In one sat a dark-haired youth of about sixteen, with a round face and moody eyes. The other held a slender, short man with delicate features.",
            "Both the boy and the man stared at the globe and the man half-hidden in shadows who was spinning it.",
            "A chuckle sounded beside the globe. A deep, bass voice rumbled through the chuckle: \"There it is, Piter. The biggest mantrap in history. And the Duke is heading straight into its jaws. Isn't it magnificent, what I, the Baron Vladimir Harkonnen, am doing?\"",
            "\"Definitely, Baron,\" said the man. His voice was a tenor with a sweet, musical quality.",
            "The fat hand came down onto the globe, stopping the spin. Now, everyone in the room could focus on the motionless surface and see that it was the kind of globe made for wealthy collectors or planetary governors of the Empire.",
            "It had 'Imperial Craftsmanship' stamped all over it. Latitude and longitude lines were inlaid with hair-fine platinum wire. The polar caps were made of the finest cloud-milk diamonds.",
            "The fat hand moved, tracing details on the surface. \"Take a look at this,\" the deep voice rumbled. \"Look closely, Piter, and you too, Feyd-Rautha, my darling: from sixty degrees north to seventy degrees south—these exquisite ripples. Their colouring: doesn't it remind you of sweet caramel?\"",
            "\"And nowhere do you see the blue of lakes or rivers or seas. And these lovely polar caps—so small. Could anyone mistake this place? Arrakis! Truly unique. A superb setting for a unique Victory.\"",
            "A smile touched Piter’s lips. \"And to think, Baron: the Padishah Emperor believes he’s given the Duke your spice planet. How touching.\"",
            "\"That’s nonsense,\" the Baron rumbled. \"You say that to confuse young Feyd-Rautha, but there's no need to confuse my nephew.\"",
            "The moody-faced youth shifted in his chair, smoothing a wrinkle in his black leotards. He sat up straight as a quiet tapping sounded at the door behind him.",
            "Piter unfolded himself from his chair, walked to the door, and cracked it wide enough to take a message cylinder. He closed the door, unrolled the cylinder, and scanned it. He chuckled. Then he chuckled again.",
            "\"Well?\" the Baron demanded.",
            "\"The idiot wrote back!\"",
            "\"Since when did an Atreides ever turn down the chance to make a grand gesture?\" the Baron asked. \"Well, what does he say?\"",
            "\"He’s incredibly rude, Baron. Calls you just 'Harkonnen'—no 'Sire and Dear Cousin,' no title, nothing.\"",
            "\"It’s a good name,\" the Baron growled, his voice betraying his impatience. \"What does dear Leto have to say?\"",
            "\"He says: 'Your offer of a meeting is refused. I have often met your treachery and everyone knows it.'\"",
            "\"And?\" the Baron asked.",
            "\"He says: 'The art of kanly still has fans in the Empire.' He signs it: 'Duke Leto of Arrakis.'\"",
            "Piter began to laugh. \"Of Arrakis! Oh, my! That is almost too rich!\"",
            "\"Shut up, Piter,\" the Baron said, and the laughter stopped as if switched off. \"Kanly, is it?\" the Baron asked. \"A vendetta, eh? And he uses the nice old word so rich in tradition to be sure I know he means it.\"",
            "\"You made the peace gesture,\" Piter said. \"The proper forms have been obeyed.\"",
            "\"For a Mentat, you talk too much, Piter,\" the Baron said.",
            "He thought: I must get rid of that one soon. He has almost outlived his usefulness.",
            "The Baron stared across the room at his mental assassin, seeing the feature that most people noticed first: the eyes, the shaded slits of blue within blue, the eyes with no white in them at all.",
            "A grin flashed across Piter’s face. It was like a mask grimacing beneath those hollow eyes. \"But, Baron! Never has revenge been more beautiful. It is seeing a plan of the most exquisite treachery: to make Leto exchange Caladan for Dune—and with no choice because the Emperor orders it. How wicked of you!\"",
            "In a cold voice, the Baron said: \"You've got a serious case of verbal diarrhoea, Piter.\"",
            "\"But I’m happy, my Baron. Whereas you... you’re just jealous.\"",
            "\"Piter!\"",
            "\"Ah-ah, Baron! Isn't it regrettable you couldn't come up with this delicious scheme by yourself?\"",
            "\"Someday I will have you strangled, Piter.\"",
            "\"Of course, Baron. Enfin! But a kind act is never lost, eh?\"",
            "\"Have you been chewing verite or semuta, Piter?\"",
            "\"Truth without fear surprises the Baron,\" Piter said. His face pulled down into a caricature of a frown. \"Ah, hah! But you see, Baron, as a Mentat I know when you will send the executioner. You will hold back just as long as I am useful. To move sooner would be wasteful and I’m still of much use. I know what it is you learned from that lovely Dune planet—waste not. True, Baron?\"",
            "The Baron continued to stare at Piter.",
            "Feyd-Rautha squirmed in his chair. These arguing fools! he thought. My uncle cannot talk to his Mentat without arguing. Do they think I’ve nothing to do except listen to their bickering?",
            "\"Feyd,\" the Baron said. \"I told you to listen and learn when I invited you in here. Are you learning?\"",
            "\"Yes, Uncle.\" The voice was carefully submissive.",
            "\"Sometimes I wonder about Piter,\" the Baron said. \"I cause pain out of necessity, but he... I swear he takes a positive delight in it. For myself, I can feel pity toward poor Duke Leto. Dr. Yueh will move against him soon, and that’ll be the end of all the Atreides. But surely Leto will know whose hand directed the pliant doctor... and knowing that will be a terrible thing.\"",
            "\"Then why haven't you told the doctor to slip a knife between his ribs quietly and efficiently?\" Piter asked. \"You talk of pity, but—\"",
            "\"The Duke must know when I seal his doom,\" the Baron said. \"And the other Great Houses must learn of it. The knowledge will make them pause. I’ll gain a bit more room to manoeuvre. The necessity is obvious, but I don’t have to like it.\"",
            "\"Room to manoeuvre,\" Piter sneered. \"Already you have the Emperor’s eyes on you, Baron. You move too boldly. One day the Emperor will send a legion or two of his Sardaukar down here onto Giedi Prime and that’ll be the end of Baron Vladimir Harkonnen.\"",
            "\"You’d like to see that, wouldn't you, Piter?\" the Baron asked. \"You’d enjoy seeing the Corps of Sardaukar pillage my cities and sack this castle. You’d truly enjoy that.\"",
            "\"Does the Baron need to ask?\" Piter whispered.",
            "\"You should’ve been a Commander in the Corps,\" the Baron said. \"You’re too interested in blood and pain. Perhaps I was too quick promising you the spoils of Arrakis.\"",
            "Piter took five curiously dainty steps into the room, stopping directly behind Feyd-Rautha. The tension in the room was tight, and the youth looked up at Piter with a worried frown.",
            "\"Don't play games with me, Baron,\" Piter said. \"You promised me the Lady Jessica. You promised her to me.\"",
            "\"For what, Piter?\" the Baron asked. \"For pain?\"",
            "Piter stared at him, dragging out the silence.",
            "Feyd-Rautha moved his floating chair to one side, said: \"Uncle, do I have to stay? You said you’d—\"",
            "\"My darling Feyd-Rautha grows impatient,\" the Baron said. He moved within the shadows beside the globe. \"Patience, Feyd.\" And he turned his attention back to the Mentat. \"What about the little Dukeling, the child Paul, my dear Piter?\"",
            "\"The trap will bring him to you, Baron,\" Piter muttered.",
            "\"That’s not my question,\" the Baron said. \"You’ll recall that you predicted the Bene Gesserit witch would bear a daughter to the Duke. You were wrong, eh, Mentat?\"",
            "\"I’m not often wrong, Baron,\" Piter said, and for the first time, you could hear the fear in his voice. \"Give me that much: I’m rarely wrong. And you know yourself these Bene Gesserit bear mostly daughters. Even the Emperor’s wife has produced only females.\"",
            "\"Uncle,\" said Feyd-Rautha, \"you said there’d be something important here for me to—\"",
            "\"Listen to my nephew,\" the Baron said. \"He wants to rule my Barony, yet he cannot rule himself.\" The Baron stirred beside the globe, a shadow amongst shadows. \"Well then, Feyd-Rautha Harkonnen, I summoned you here hoping to teach you a bit of wisdom. Have you observed our good Mentat? You should’ve learned something from this exchange.\"",
            "\"But, Uncle—\"",
            "\"A most efficient Mentat, Piter, wouldn't you say, Feyd?\"",
            "\"Yes, but—\"",
            "\"Ah! Indeed but! But he eats too much spice, pops it like sweets. Look at his eyes! He looks like he's just clocked off a shift in the Arrakeen labour pool. Efficient, Piter, but he’s still emotional and prone to passionate outbursts. Efficient, Piter, but he can still make mistakes.\"",
            "Piter spoke in a low, sullen tone: \"Did you call me in here just to ruin my efficiency with criticism, Baron?\"",
            "\"Ruin your efficiency? You know me better than that, Piter. I only wish for my nephew to understand the limitations of a Mentat.\"",
            "\"Are you already training my replacement?\" Piter demanded.",
            "\"Replace you? Why, Piter, where could I find another Mentat with your cunning and venom?\"",
            "\"The same place you found me, Baron.\"",
            "\"Perhaps I should at that,\" the Baron mused. \"You do seem a bit unstable lately. And the spice you eat!\"",
            "\"Are my pleasures too expensive, Baron? Do you object to them?\"",
            "\"My dear Piter, your pleasures are what tie you to me. How could I object to that? I merely wish my nephew to observe this about you.\"",
            "\"Then I’m on display,\" Piter said. \"Shall I dance? Shall I perform my various functions for the eminent Feyd-Rau—\"",
            "\"Precisely,\" the Baron said. \"You are on display. Now, be silent.\"",
            "He glanced at Feyd-Rautha, noting his nephew’s lips, the full and pouting look of them, the Harkonnen genetic marker, now twisted slightly in amusement.",
            "\"This is a Mentat, Feyd. It has been trained and conditioned to perform certain duties. The fact that it’s encased in a human body, however, must not be overlooked. A serious drawback, that. I sometimes think the ancients with their thinking machines had the right idea.\"",
            "\"They were toys compared to me,\" Piter snarled. \"You yourself, Baron, could outperform those machines.\"",
            "\"Perhaps,\" the Baron said. \"Ah, well...\" He took a deep breath and belched. \"Now, Piter, outline for my nephew the main features of our campaign against the House of Atreides. Function as a Mentat for us, if you please.\"",
            "\"Baron, I’ve warned you not to trust one so young with this information. My observations of—\"",
            "\"I’ll be the judge of that,\" the Baron said. \"I’m giving you an order, Mentat. Do your job.\"",
            "\"So be it,\" Piter said. He straightened up, assuming an odd attitude of dignity—as though it were another mask, but this time clothing his entire body.",
            "\"In a few days Standard, the entire household of Duke Leto will embark on a Spacing Guild liner for Arrakis. The Guild will drop them at the city of Arrakeen rather than at our city of Carthag. The Duke’s Mentat, Thufir Hawat, will have concluded rightly that Arrakeen is easier to defend.\"",
            "\"Listen carefully, Feyd,\" the Baron said. \"Observe the plans within plans within plans.\"",
            "Feyd-Rautha nodded, thinking: This is more like it. The old monster is letting me in on secret things at last. He must really mean for me to be his heir.",
            "\"There are several side possibilities,\" Piter said. \"I indicate that House Atreides will go to Arrakis. We must not, however, ignore the possibility the Duke has contracted with the Guild to move him to a place of safety outside the System. Others in similar circumstances have become renegade Houses, taking family atomics and shields and fleeing beyond the Imperium.\"",
            "\"The Duke’s too proud a man for that,\" the Baron said.",
            "\"It is a possibility,\" Piter said. \"The ultimate effect for us would be the same, however.\"",
            "\"No, it would not!\" the Baron growled. \"I must have him dead and his line ended.\"",
            "\"That’s the high probability,\" Piter said. \"There are certain preparations that indicate when a House is going renegade. The Duke appears to be doing none of these things.\"",
            "\"So,\" the Baron sighed. \"Get on with it, Piter.\"",
            "\"At Arrakeen,\" Piter said, \"the Duke and his family will occupy the Residency, lately the home of Count and Lady Fenring.\"",
            "\"The Ambassador to the Smugglers,\" the Baron chuckled.",
            "\"Ambassador to what?\" Feyd-Rautha asked.",
            "\"Your uncle makes a joke,\" Piter said. \"He calls Count Fenring 'Ambassador to the Smugglers', indicating the Emperor’s interest in smuggling operations on Arrakis.\"",
            "Feyd-Rautha turned a puzzled stare on his uncle. \"Why?\"",
            "\"Don’t be dense, Feyd,\" the Baron snapped. \"As long as the Guild remains effectively outside Imperial control, how could it be otherwise? How else could spies and assassins move about?\"",
            "Feyd-Rautha’s mouth made a soundless \"Oh-h-h-h.\"",
            "\"We’ve arranged diversions at the Residency,\" Piter said. \"There’ll be an attempt on the life of the Atreides heir—an attempt which could succeed.\"",
            "\"Piter,\" the Baron rumbled, \"you indicated—\"",
            "\"I indicated accidents can happen,\" Piter said. \"And the attempt must appear valid.\"",
            "\"Ah, but the lad has such a sweet young body,\" the Baron said. \"Of course, he’s potentially more dangerous than the father... with that witch mother training him. Accursed woman! Ah, well, please continue, Piter.\"",
            "\"Hawat will have guessed that we have an agent planted on him,\" Piter said. \"The obvious suspect is Dr. Yueh, who is indeed our agent. But Hawat has investigated and found that our doctor is a Suk School graduate with Imperial Conditioning—supposedly safe enough to treat even the Emperor.\"",
            "\"Great store is set on Imperial Conditioning. It’s assumed that ultimate conditioning cannot be removed without killing the subject. However, as someone once observed, given the right lever you can move a planet. We found the lever that moved the doctor.\"",
            "\"How?\" Feyd-Rautha asked. He found this a fascinating subject. Everyone knew you couldn't break Imperial Conditioning!",
            "\"Another time,\" the Baron said. \"Continue, Piter.\"",
            "\"In place of Yueh,\" Piter said, \"we’ll drag a most interesting suspect across Hawat’s path. The very audacity of this suspect will recommend her to Hawat’s attention.\"",
            "\"Her?\" Feyd-Rautha asked.",
            "\"The Lady Jessica herself,\" the Baron said.",
            "\"Is it not sublime?\" Piter asked. \"Hawat’s mind will be so filled with this prospect it’ll ruin his function as a Mentat. He may even try to kill her.\"",
            "Piter frowned, then added: \"But I don’t think he’ll be able to pull it off.\"",
            "\"You don’t want him to, eh?\" the Baron asked.",
            "\"Don’t distract me,\" Piter said. \"While Hawat is occupied with the Lady Jessica, we’ll divert him further with uprisings in a few garrison towns and the like. These will be put down. The Duke must believe he’s gaining a measure of security. Then, when the moment is ripe, we’ll signal Yueh and move in with our major force... ah...\"",
            "\"Go ahead, tell him all of it,\" the Baron said.",
            "\"We’ll move in strengthened by two legions of Sardaukar disguised in Harkonnen uniforms.\"",
            "\"Sardaukar!\" Feyd-Rautha breathed. His mind focused on the dread Imperial troops, the killers without mercy, the soldier fanatics of the Padishah Emperor.",
            "\"You see how I trust you, Feyd,\" the Baron said. \"No hint of this must ever reach another Great House, or the Landsraad might unite against the Imperial House and there’d be chaos.\"",
            "\"The main point,\" Piter said, \"is this: since House Harkonnen is being used to do the Imperial dirty work, we’ve gained a true advantage. It’s a dangerous advantage, to be sure, but if used cautiously, it will bring House Harkonnen greater wealth than that of any other House in the Imperium.\"",
            "\"You have no idea how much wealth is involved, Feyd,\" the Baron said. \"Not in your wildest dreams. To begin with, we’ll have an irrevocable directorship in the CHOAM Company.\"",
            "Feyd-Rautha nodded. Wealth was the thing. CHOAM was the key to wealth, each noble House dipping from the company’s coffers whatever it could under the power of the directorships. Those CHOAM directorships—they were the real evidence of political power in the Imperium, shifting with the voting strength within the Landsraad as it balanced itself against the Emperor and his supporters.",
            "\"The Duke Leto,\" Piter said, \"may attempt to flee to the new Fremen scum along the desert’s edge. Or he may try to send his family into that imagined security. But that path is blocked by one of His Majesty’s agents—the planetary ecologist. You may remember him—Kynes.\"",
            "\"Feyd remembers him,\" the Baron said. \"Get on with it.\"",
            "\"You do not drool very prettily, Baron,\" Piter said.",
            "\"Get on with it, I command you!\" the Baron roared.",
            "Piter shrugged. \"If things go to plan,\" he said, \"House Harkonnen will have a sub-fief on Arrakis within a Standard year. Your uncle will have control of that fief. His own personal agent will rule on Arrakis.\"",
            "\"More profits,\" Feyd-Rautha said.",
            "\"Indeed,\" the Baron said.",
            "And he thought: It’s only fair. We’re the ones who tamed Arrakis... except for the few mongrel Fremen hiding in the skirts of the desert... and some tame smugglers bound to the planet almost as tightly as the native labour pool.",
            "\"And the Great Houses will know that the Baron has destroyed the Atreides,\" Piter said. \"They will know.\"",
            "\"They will know,\" the Baron breathed.",
            "\"Loveliest of all,\" Piter said, \"is that the Duke will know, too. He knows now. He can already feel the trap.\"",
            "\"It’s true the Duke knows,\" the Baron said, and his voice held a note of sadness. \"He could not help but know... more’s the pity.\"",
            "The Baron moved out and away from the globe of Arrakis. As he emerged from the shadows, his figure took on dimension—grossly and immensely fat.",
            "Subtle bulges beneath the folds of his dark robes revealed that all this fat was supported partly by portable suspensors harnessed to his flesh. He might weigh two hundred Standard kilos in reality, but his feet would carry no more than fifty of them.",
            "\"I am hungry,\" the Baron rumbled, rubbing his protruding lips with a ring-covered hand, staring down at Feyd-Rautha through fat-enfolded eyes. \"Send for food, my darling. We will eat before we retire.\"",
            "CHAPTER 3",
            "So said St. Alia-of-the-Knife: \"The Reverend Mother must combine the seductive wiles of a courtesan with the untouchable majesty of a virgin goddess. She must hold these opposing traits in tension as long as her youth lasts.",
            "\"For when youth and beauty are gone, she will find that the space between, once held by tension, has become a wellspring of cunning and resourcefulness.\"",
            "—from ‘Muad’Dib, Family Commentaries’ by the Princess Irulan",
            "\"Well, Jessica, what have you got to say for yourself?\" asked the Reverend Mother.",
            "It was near sunset at Castle Caladan on the day of Paul’s ordeal. The two women were alone in Jessica’s morning room, while Paul waited in the soundproofed Meditation Chamber next door.",
            "Jessica stood facing the south windows. She saw, yet didn't really see, the evening colours settling across the meadow and river. She heard, yet didn't really hear, the Reverend Mother’s question.",
            "There had been another ordeal once—so many years ago. A skinny girl with bronze-coloured hair, her body tortured by the pains of puberty, had entered the study of the Reverend Mother Gaius Helen Mohiam at the Bene Gesserit school on Wallach IX.",
            "Jessica looked down at her right hand and flexed the fingers, remembering the pain, the terror, the anger.",
            "\"Poor Paul,\" she whispered.",
            "\"I asked you a question, Jessica!\" The old woman’s voice was snappy and demanding.",
            "\"What? Oh...\" Jessica tore her attention away from the past and faced the Reverend Mother, who sat with her back to the stone wall between the two west windows. \"What do you want me to say?\"",
            "\"What do I want you to say? What do I want you to say?\" The old voice mimicked her cruelly.",
            "\"So I had a son!\" Jessica flared. She knew she was being provoked into this anger on purpose.",
            "\"You were told to bear only daughters to the Atreides.\"",
            "\"It meant the world to him,\" Jessica pleaded.",
            "\"And you, in your pride, thought you could produce the Kwisatz Haderach!\"",
            "Jessica lifted her chin. \"I sensed it was possible.\"",
            "\"You thought only of your Duke’s desire for a son,\" the old woman snapped. \"And his desires don't matter here. An Atreides daughter could’ve been wed to a Harkonnen heir and healed the rift. You’ve hopelessly complicated things. We may lose both bloodlines now.\"",
            "\"You’re not perfect,\" Jessica said. She braved the steady stare from the old eyes.",
            "Eventually, the old woman muttered: \"What’s done is done.\"",
            "\"I swore I’d never regret my decision,\" Jessica said.",
            "\"How noble,\" the Reverend Mother sneered. \"No regrets. We shall see about that when you’re a fugitive with a price on your head, and everyone is out to kill you and your son.\"",
            "Jessica went pale. \"Is there no other way?\"",
            "\"Another way? A Bene Gesserit shouldn't have to ask that.\"",
            "\"I only ask what you see in the future with your superior abilities.\"",
            "\"I see in the future what I’ve seen in the past. You know the pattern of our affairs well enough, Jessica. The race knows its own mortality and fears its heredity getting stagnant. It’s in the bloodstream—the urge to mix genetic strains without a plan. The Imperium, the CHOAM Company, all the Great Houses... they are just driftwood in the path of the flood.\"",
            "\"CHOAM,\" Jessica muttered. \"I suppose it’s already decided how they’ll carve up the profits from Arrakis.\"",
            "\"What is CHOAM but the weather vane of our times?\" the old woman said. \"The Emperor and his friends now command fifty-nine point six-five percent of the CHOAM directorship’s votes. They certainly smell profit, and as others smell those same profits, his voting strength will increase. That is the pattern of history, girl.\"",
            "\"That’s certainly what I need right now,\" Jessica said. \"A history lesson.\"",
            "\"Don't be cheeky, girl! You know as well as I do what forces surround us. We’ve got a three-point civilisation: the Imperial Household balanced against the Great Houses of the Landsraad, and between them, the Guild with its damnable monopoly on interstellar transport. In politics, a tripod is the most unstable structure of all. It’d be bad enough without the complication of a feudal trade culture that turns its back on most science.\"",
            "Jessica spoke bitterly: \"Woodchips in the path of the flood—and this chip here is Duke Leto, and this one’s his son, and this one’s—\"",
            "\"Oh, shut it, girl. You went into this knowing exactly how narrow the ledge was you were walking on.\"",
            "\"'I am Bene Gesserit: I exist only to serve,'\" Jessica quoted.",
            "\"Truth,\" the old woman said. \"And all we can hope for now is to stop this from blowing up into a total disaster, and salvage what we can of the key bloodlines.\"",
            "Jessica closed her eyes, feeling tears pressing against her lids. She fought down the internal trembling, the external shaking, the uneven breathing, the ragged pulse, the sweaty palms.",
            "Eventually, she said, \"I’ll pay for my own mistake.\"",
            "\"And your son will pay with you.\"",
            "\"I’ll protect him as best I can.\"",
            "\"Protect!\" the old woman snapped. \"You know the weakness in that! Protect your son too much, Jessica, and he’ll never grow strong enough to fulfil any destiny.\"",
            "Jessica turned away and looked out the window at the gathering darkness. \"Is it really that terrible, this planet Arrakis?\"",
            "\"Bad enough, but not entirely. The Missionaria Protectiva has been in there and softened things up a bit.\" The Reverend Mother hauled herself to her feet and straightened a fold in her gown. \"Call the boy in. I have to leave soon.\"",
            "\"Do you have to?\"",
            "The old woman’s voice softened. \"Jessica, girl, I wish I could stand in your place and take your suffering. But each of us has to make her own path.\"",
            "\"I know.\"",
            "\"You mean as much to me as any of my own daughters, but I cannot let that interfere with duty.\"",
            "\"I understand... the necessity.\"",
            "\"What you did, Jessica, and why you did it—we both know. But kindness forces me to tell you there’s little chance your lad will be the Bene Gesserit Totality. You mustn't let yourself hope too much.\"",
            "Jessica shook tears from the corners of her eyes. It was an angry gesture. \"You make me feel like a little girl again—reciting my first lesson.\"",
            "She forced the words out: \"'Humans must never submit to animals.'\"",
            "A dry sob shook her. In a low voice, she said: \"I’ve been so lonely.\"",
            "\"That should be one of the tests,\" the old woman said. \"Humans are almost always lonely. Now, call the boy. He’s had a long, frightening day. But he’s had time to think and remember, and I must ask the other questions about these dreams of his.\"",
            "Jessica nodded, went to the door of the Meditation Chamber, and opened it. \"Paul, come in now, please.\"",
            "Paul emerged with a stubborn slowness. He stared at his mother as though she were a stranger. Wariness veiled his eyes when he glanced at the Reverend Mother, but this time he nodded to her—the nod one gives an equal. He heard his mother close the door behind him.",
            "\"Young man,\" the old woman said, \"let’s get back to this dream business.\"",
            "\"What do you want?\"",
            "\"Do you dream every night?\"",
            "\"Not dreams worth remembering. I can remember every dream, but some are worth remembering and some aren't.\"",
            "\"How do you know the difference?\"",
            "\"I just know.\"",
            "The old woman glanced at Jessica, then back to Paul. \"What did you dream last night? Was it worth remembering?\"",
            "\"Yes.\" Paul closed his eyes. \"I dreamed of a cavern... and water... and a girl there—very skinny with big eyes. Her eyes are all blue, no whites in them at all. I talk to her and tell her about you, about seeing the Reverend Mother on Caladan.\"",
            "Paul opened his eyes.",
            "\"And the thing you tell this strange girl about seeing me—did it happen today?\"",
            "Paul thought about this, then said: \"Yes. I tell the girl you came and put a stamp of strangeness on me.\"",
            "\"Stamp of strangeness,\" the old woman breathed, and again she shot a look at Jessica, before returning her attention to Paul. \"Tell me truly now, Paul, do you often have dreams of things that happen afterwards exactly as you dreamed them?\"",
            "\"Yes. And I’ve dreamed about that girl before.\"",
            "\"Oh? You know her?\"",
            "\"I will know her.\"",
            "\"Tell me about her.\"",
            "Again, Paul closed his eyes. \"We’re in a little place in some rocks where it’s sheltered. It’s almost night, but it’s hot and I can see patches of sand out of an opening in the rocks. We’re... waiting for something... for me to go meet some people. And she’s frightened but trying to hide it from me, and I’m excited. And she says: 'Tell me about the waters of your homeworld, Usul.'\"",
            "Paul opened his eyes. \"Isn't that strange? My homeworld is Caladan. I’ve never even heard of a planet called Usul.\"",
            "\"Is there more to this dream?\" Jessica prompted.",
            "\"Yes. But maybe she was calling me Usul,\" Paul said. \"I just thought of that.\"",
            "Again, he closed his eyes. \"She asks me to tell her about the waters. And I take her hand. And I say I’ll tell her a poem. And I tell her the poem, but I have to explain some of the words—like beach and surf and seaweed and seagulls.\"",
            "\"What poem?\" the Reverend Mother asked.",
            "Paul opened his eyes. \"It’s just one of Gurney Halleck’s tone poems for sad times.\"",
            "Behind Paul, Jessica began to recite:",
            "I remember salt smoke from a beach fire\nAnd shadows under the pines—\nSolid, clean... fixed—\nSeagulls perched at the tip of land,\nWhite upon green...\nAnd a wind comes through the pines\nTo sway the shadows;\nThe seagulls spread their wings,\nLift\nAnd fill the sky with screeches.\nAnd I hear the wind\nBlowing across our beach,\nAnd the surf,\nAnd I see that our fire\nHas scorched the seaweed.",
            "\"That’s the one,\" Paul said.",
            "The old woman stared at Paul, then said: \"Young man, as a Proctor of the Bene Gesserit, I seek the Kwisatz Haderach, the male who truly can become one of us. Your mother sees this possibility in you, but she sees with the eyes of a mother. I see the possibility too, but nothing more.\"",
            "She fell silent, and Paul saw that she wanted him to speak. He waited her out.",
            "Eventually, she said: \"As you wish, then. You’ve got depths in you; I’ll grant you that.\"",
            "\"May I go now?\" he asked.",
            "\"Don't you want to hear what the Reverend Mother can tell you about the Kwisatz Haderach?\" Jessica asked.",
            "\"She said those who tried for it died.\"",
            "\"But I can help you with a few hints at why they failed,\" the Reverend Mother said.",
            "She talks of hints, Paul thought. She doesn't really know anything.",
            "He said: \"Hint then.\"",
            "\"And be damned to me?\" She smiled wryly, a criss-cross of wrinkles on her old face. \"Very well: 'That which submits rules.'\"",
            "He felt astonishment: she was talking about such elementary things as tension within meaning. Did she think his mother had taught him nothing at all?",
            "\"That’s a hint?\" he asked.",
            "\"We’re not here to bandy words or quibble over their meaning,\" the old woman said. \"The willow submits to the wind and prospers until one day it is many willows—a wall against the wind. This is the willow’s purpose.\"",
            "Paul stared at her. She said purpose and he felt the word hit him, re-infecting him with terrible purpose. He experienced a sudden anger at her: silly old witch with her mouth full of platitudes.",
            "\"You think I could be this Kwisatz Haderach,\" he said. \"You talk about me, but you haven't said a single thing about what we can do to help my father. I’ve heard you talking to my mother. You talk as though my father is already dead. Well, he isn't!\"",
            "\"If there were anything to be done for him, we’d have done it,\" the old woman growled. \"We might be able to save you. Doubtful, but possible. But for your father, nothing. When you’ve learned to accept that as a fact, you’ve learned a real Bene Gesserit lesson.\"",
            "Paul saw how the words shook his mother. He glared at the old woman. How could she say such a thing about his father? What made her so sure? His mind seethed with resentment.",
            "The Reverend Mother looked at Jessica. \"You’ve been training him in the Way—I’ve seen the signs of it. I’d have done the same in your shoes, and sod the Rules.\"",
            "Jessica nodded.",
            "\"Now, I warn you,\" said the old woman, \"ignore the regular order of training. He needs the Voice for his own safety. He already has a good start in it, but we both know how much more he needs... and how desperately.\"",
            "She stepped close to Paul and stared down at him. \"Goodbye, young human. I hope you make it. But if you don't—well, we shall succeed eventually.\"",
            "Once more she looked at Jessica. A flicker of understanding passed between them. Then the old woman swept from the room, her robes hissing, without another backward glance. The room and its occupants were already shut from her thoughts.",
            "But Jessica had caught one glimpse of the Reverend Mother’s face as she turned away.",
            "There had been tears on her wrinkled cheeks.",
            "The tears were more unnerving than any other word or sign that had passed between them that day."
        ]
    }
};

