
export type BookSegment = string | { text: string; type: "story" | "commentary" };

export const books: Record<string, { title: string; content: BookSegment[] }> = {
    "security-plus": {
        title: "CompTIA Security+ Study Guide",
        content: [
            "CHAPTER 1: SECURITY CONTROLS (THE BRITISH EDITION)",
            { text: "Rewritten in Everyday Modern British English (Now with Extra Banter)", type: "commentary" },
            { text: "Note: This guide breaks down the exam objectives for Domain 1.0 using proper British slang to make it stick better than a biscuit in tea.", type: "commentary" },
            "INTRODUCTION",
            { text: "In today's world, keeping your digital gaff (place) safe is a massive job. You can't just slap a rusty padlock on the front door and head down the pub for a pint and a packet of crisps; you need proper layers of protection. Security controls are the bread and butter (or fish and chips) of any decent security setup. They help you stop things going pear-shaped (wrong), spot when some chancer is trying to pull a fast one, and make sure you aren't breaking the law.", type: "story" },
            { text: "This chapter covers the first exam objective in Domain 1.0. We'll have a butcher's (look) at the different types of controls—Technical, Managerial, Operational, and Physical. Then we'll suss out what they actually do—like stopping trouble before it starts (Preventive) or mopping up the spilt milk afterwards (Corrective).", type: "story" },
            { text: "Security controls are just the tools and rules companies use to protect themselves. Think of it like securing your house: you lock the door (Preventive), put up a \"Beware of the Mother-in-Law\" sign (Deterrent), and maybe install a camera to see which neighbour is pinching your milk (Detective).", type: "commentary" },
            "CONTROL CATEGORIES (THE BIG FOUR)",
            { text: "There are four main buckets we throw these controls into. Each one handles a different part of the business to keep things running tickety-boo.", type: "story" },
            "1. Technical Controls (The Techy Stuff)",
            { text: "This is the gear implemented by the IT crowd. It's all about using wizardry and technology to stop the bad actors (hackers in hoodies) from getting into your systems.", type: "story" },
            { text: "Firewalls: These are your digital bouncers. They stand at the door of your network, arms folded, checking everyone's ID. If you're not on the list or your trainers look a bit dodgy, you're not getting in. They filter out the rubbish and stop intruders dead in their tracks.", type: "story" },
            { text: "Data Encryption: This turns your important info into complete gobbledygook (nonsense). If some wrong 'un manages to nick (steal) your data, they won't be able to read it without the secret key. It's like writing a letter in secret code so the nosey postman can't read your gossip.", type: "story" },
            { text: "Technical controls are software or hardware tools. If it involves code, flashing lights, or a machine doing the heavy lifting, it's usually a Technical control.", type: "commentary" },
            "2. Managerial Controls (The Suits)",
            { text: "This is the stuff handled by the bigwigs (bosses). It involves risk assessments, writing the rulebook, and making sure everyone is towing the line. It's about planning and organising so the business doesn't go bust and end up on the news.", type: "story" },
            { text: "Performance Reviews: Checking if staff are pulling their weight or just pretending to work while playing Solitaire. It's a way to make sure everyone is doing their job properly and not slacking off.", type: "story" },
            { text: "Risk Assessments: This is basically doom-scrolling for business. You sit down and work out what could go wrong. \"What if the servers catch fire?\" \"What if Dave from Accounts clicks a link for 'Free iPhones'?\" It's spotting trouble before it lands on your doorstep.", type: "story" },
            { text: "Code of Conduct: The rulebook. It tells employees how to behave so they don't act like absolute plonkers and cause a scandal.", type: "story" },
            { text: "Managerial controls are the \"paperwork\" and \"decisions\" side of security. Policies, laws, huge PDF documents nobody reads, and reviews fall here.", type: "commentary" },
            "3. Operational Controls (The Daily Grind)",
            { text: "These are the things done by actual humans on a day-to-day basis. It's the practical stuff to keep the lights on and the data safe.", type: "story" },
            { text: "Incident Response Procedures: The master plan for when the muck hits the fan. If you get hacked, this is the step-by-step guide on how to fix it without running around like a headless chicken screaming \"We're doomed!\"", type: "story" },
            { text: "Security Awareness Training: Teaching staff not to be daft. It's showing them how to spot a phishing email so Barry in Sales doesn't download a virus thinking he's won the Nigerian lottery. It helps build a culture where everyone is security-conscious.", type: "story" },
            { text: "User Access Management: Making sure people only have the keys to the rooms they need. You wouldn't give the cleaner the combination to the main safe, would you? This ensures users only access what they need for their job and nothing juicier.", type: "story" },
            { text: "Operational controls are executed by people. If a human has to get off their backside and do something (like attend training or follow a checklist), it's Operational.", type: "commentary" },
            "4. Physical Controls (Bricks and Mortar)",
            { text: "This is the stuff you can actually kick (though we don't recommend it). It protects the real-world assets—buildings, servers, and staff—from being tampered with or stolen.", type: "story" },
            { text: "Access Control Vestibule: A fancy name for a \"mantrap.\" It sounds like something from a spy film, but it's just a small room with two doors. You open the first one, step in, and the first one has to lock before the second one opens. Stops sneaky people tailgating you into the office to steal the biscuits.", type: "story" },
            { text: "Biometric Locks: Using your fingerprint or face to open a door. Very James Bond, until you have a plaster on your finger and get locked out in the rain.", type: "story" },
            { text: "Guards: Big lads on the door. They act as a visual deterrent—nobody wants to mess with a 6ft security guard named \"Tiny\".", type: "story" },
            { text: "Security Fences: Big metal fences to stop people climbing in. Sometimes they have barbed wire if you really want to keep the riff-raff out.", type: "story" },
            { text: "CCTV: Cameras watching your every move. Useful for spotting intruders or seeing who scratched your car in the car park (it was probably Dave).", type: "story" },
            { text: "Vehicle Barriers: Bollards or gates to stop someone driving a white van straight through the front door.", type: "story" },
            { text: "Panic Buttons: A button under the desk you can mash if it all kicks off.", type: "story" },
            { text: "If you can touch it, it's a Physical control. Fences, locks, cameras, guards, dogs, moats with sharks (optional).", type: "commentary" },
            "CONTROL TYPES (WHAT THEY ACTUALLY DO)",
            { text: "Now we know what the controls are, let's look at how they function. This is essential for the exam, so don't skim it or you'll be gutted later.", type: "story" },
            "1. Preventive Controls (Stopping the Rot)",
            { text: "These stop the bad thing from happening in the first place. Like an umbrella stops you getting wet.", type: "story" },
            { text: "Example: A firewall stops a hacker getting in. Training staff stops them clicking dodgy links.", type: "story" },
            { text: "Shutting the stable door before the horse bolts.", type: "commentary" },
            "2. Deterrent Controls (The Scare Tactics)",
            { text: "These don't physically stop you, but they make you think twice. They rely on the bad guy being scared of the consequences.", type: "story" },
            { text: "Example: A \"CCTV in Operation\" sign. Even if the camera is actually a dummy one from the pound shop, the sign might scare a burglar off. A big guard standing with his arms folded looking mean.", type: "story" },
            { text: "Putting the frighteners on someone.", type: "commentary" },
            "3. Detective Controls (The Sherlock Holmes Bit)",
            { text: "These spot the problem while it's happening or after it's happened. They don't stop it, but they ring the alarm so you know you've been done over.", type: "story" },
            { text: "Example: A burglar alarm going off at 3 AM. Checking the logs to see who deleted the payroll file. CCTV recording a crime in HD.", type: "story" },
            { text: "Catching someone red-handed with their hand in the biscuit tin.", type: "commentary" },
            "4. Corrective Controls (The Clean Up)",
            { text: "These fix the mess after the damage is done. The digital dustpan and brush.", type: "story" },
            { text: "Example: Restoring your data from a backup after a virus wipes your PC. Installing a patch to fix a security hole so it doesn't happen again.", type: "story" },
            { text: "Picking up the pieces.", type: "commentary" },
            "5. Compensating Controls (Plan B)",
            { text: "Sometimes you can't afford the proper expensive security, or the tech doesn't work. So you put a \"Compensating Control\" in place—a temporary fix or an alternative.", type: "story" },
            { text: "Example: You can't afford a fancy smart card system, so you make the reception guards check everyone's ID badge manually instead.", type: "story" },
            { text: "Making do. A bit of a bodge job, but it works.", type: "commentary" },
            "6. Directive Controls (Do As You're Told)",
            { text: "These are rules and instructions. They tell people how to behave. It's the \"Because I said so\" of security.", type: "story" },
            { text: "Example: A policy that says \"Don't stick unknown USB drives in the computers.\" Standard Operating Procedures (SOPs).", type: "story" },
            { text: "The rulebook.", type: "commentary" },
            { text: "Prevent: Stop it.\nDeter: Scare them off.\nDetect: Spot the rotter.\nCorrect: Fix the mess.\nCompensate: The workaround.\nDirective: The rules.", type: "commentary" },
            "CHAPTER REVIEW QUESTIONS (PUB QUIZ TIME)",
            { text: "Let's see if you've been paying attention or just nodding off in the back. Grab a pen!", type: "story" },
            { text: "1. A company has guards at the gate, guards at the front door, and a mantrap inside. To get to the data room, you need to get through two more doors with special locks. What two types of control is the company using?", type: "story" },
            { text: "Preventive (stopping access) and Physical (guards/doors). They are physically stopping you from getting in. No entry!", type: "commentary" },
            { text: "2. A server gets attacked. The IT admin starts digging through the log files to see what happened. What control is this?", type: "story" },
            { text: "Detective. He's looking for clues to find out what went down. Elementary, my dear Watson.", type: "commentary" },
            { text: "3. The boss tells the mail admin and network admin to write up a \"Standard Operating Procedure\" (SOP). What type of control is this task?", type: "story" },
            { text: "Directive (or Managerial). It's creating a set of instructions for people to follow. Boring, but necessary.", type: "commentary" },
            { text: "4. Which control is all about stopping threats before they cause grief?", type: "story" },
            { text: "Preventive. Nipping it in the bud.", type: "commentary" },
            { text: "5. Microsoft tells you there's a critical update for Windows 11. Your security team installs it immediately. What control is this?", type: "story" },
            { text: "Corrective. You are fixing a vulnerability (a hole) in the software. Note: Some might argue preventive, but patching is often seen as correcting a flaw.", type: "commentary" },
            { text: "6. You got hit by ransomware because a tech control failed. You want to stop it happening again. What do you implement?", type: "story" },
            { text: "Corrective. You are fixing the issue to prevent reoccurrence. Wait, actually, if the question asks what to implement to prevent reoccurrence, the goal is Preventive, but the act of fixing the gap is corrective. (Check your specific exam guide nuances here, but usually, patching is corrective, new firewalls are preventive).", type: "commentary" },
            { text: "7. Which physical controls would stop someone wandering into a quarry?", type: "story" },
            { text: "Fences (Barriers) and Signs. Fences physically stop them; signs deter them (warn them off). \"Keep Out, Trespassers Will Be Composted.\"", type: "commentary" },
            { text: "8. An audit says you need to add more instructions to your compliance policy. What control is this?", type: "story" },
            { text: "Directive. It's adding more rules to the book.", type: "commentary" },
            { text: "9. An admin uses a fancy encryption method (homomorphic) so they can use data without decrypting it. What control category is this?", type: "story" },
            { text: "Technical. It's a tech solution involving algorithms and code. Proper nerd stuff.", type: "commentary" },
            { text: "10. Which category is in charge of setting up protocols and guidelines for the organization?", type: "story" },
            { text: "Managerial. The bosses setting the rules from their corner offices.", type: "commentary" },
            "CHAPTER 2: FUNDAMENTAL SECURITY CONCEPTS (THE BRITISH EDITION)",
            { text: "Rewritten in Everyday Modern British English", type: "story" },
            { text: "We're diving into Domain 1.0, Objective 1.2. Grab a brew, this covers the bread and butter of keeping things secure.", type: "commentary" },
            "INTRODUCTION",
            { text: "Right then, Chapter 1 was about the tools; Chapter 2 is about the ideas. We're looking at the big concepts that stop your digital life going down the swanny. We'll cover the CIA Triad (not the spies), Zero Trust (trusting nobody), and Deception technology (setting traps for the bad guys).", type: "story" },
            "THE CIA TRIAD (THE HOLY TRINITY)",
            { text: "In the security world, everything revolves around three things. If you mess one of these up, you're in for a right pickle.", type: "story" },
            { text: "Confidentiality: Keeping your secrets secret. It ensures that only the people who should see the data can see it. It's like whispering gossip to your best mate and making sure the town busybody didn't hear.", type: "story" },
            { text: "Integrity: Making sure nobody has messed with your data. If you send an email saying \"Pay Dave £10\", you don't want someone changing it to \"Pay Dave £10,000\". Integrity uses things like hashing to prove the data hasn't been fiddled with.", type: "story" },
            { text: "Availability: Making sure the systems are actually working when you need them. It's no good having the most secure website in the world if it crashes every time someone tries to log in.", type: "story" },
            { text: "Confidentiality = No peeking. Integrity = No touching. Availability = No crashing.", type: "commentary" },
            "NON-REPUDIATION (YOU SIGNED IT, MATE)",
            { text: "This is a fancy way of saying \"You can't deny you did it.\" If you sign a contract or send a secure email with a digital signature, you can't turn around later and say, \"Wasn't me, gov.\" It provides proof of who did what.", type: "story" },
            "AAA (THE BOUNCER PROTOCOLS)",
            { text: "If you want to get into a club (or a server), you have to go through the AAA process.", type: "story" },
            { text: "Authentication: This is the bouncer asking, \"Who are you?\" You show your ID (username) and prove it's you (password/PIN).", type: "story" },
            { text: "Authorization: The bouncer checks the clipboard. \"Are you on the list?\" Just because you are Dave doesn't mean you're allowed in the VIP area. This decides what you can actually do once you're in.", type: "story" },
            { text: "Accounting: The bouncer writes down what time you came in and what time you left. It's logging everything so if something goes missing, they know who was in the building.", type: "story" },
            { text: "We use protocols like RADIUS (Remote Authentication Dial-In User Service) and TACACS+ to handle this stuff securely.", type: "commentary" },
            "ZERO TRUST (TRUST NO ONE)",
            { text: "The old way of thinking was: \"If you're inside the office building, you must be a good guy.\" The new way is Zero Trust.", type: "story" },
            { text: "It basically means: \"I don't care if you're the CEO or the cleaner, and I don't care if you're in the office or working from a café in Benidorm. I'm checking your ID every single time you try to open a file.\" Never trust, always verify.", type: "story" },
            "PHYSICAL SECURITY (BOLLARDS AND BLOKES)",
            { text: "This is about stopping people physically breaking in.", type: "story" },
            { text: "Bollards: Those sturdy concrete or metal posts you see outside buildings. They stop someone driving a lorry through the front window.", type: "story" },
            { text: "Access Control Vestibule: The posh word for a mantrap. A small room with two doors; one locks before the other opens. Stops tailgaters.", type: "story" },
            { text: "CCTV: Cameras everywhere. Smile, you're on candid camera.", type: "story" },
            { text: "Lighting: Bad guys hate bright lights. Light up the car park like a Christmas tree to scare them off.", type: "story" },
            { text: "Sensors: Things that go \"beep\" when you walk past. Infrared (heat), Microwave (movement), Ultrasonic (sound).", type: "story" },
            "DECEPTION TECHNOLOGY (SETTING TRAPS)",
            { text: "Sometimes the best defence is a trap.", type: "story" },
            { text: "Honeypot: A fake server that looks full of juicy data but is actually a trap. You leave it open on purpose to lure hackers in so you can watch what they do. Like leaving a fake wallet on the pavement to see who nicks it.", type: "story" },
            { text: "Honeynet: A whole network of honeypots. A minefield for hackers.", type: "story" },
            { text: "Honeyfile: A file named \"Passwords.txt\" on your desktop. It's fake, but if anyone opens it, an alarm goes off. Gotcha!", type: "story" },
            "CHAPTER 2 REVIEW QUESTIONS (PUB QUIZ TIME)",
            { text: "1. An IT administrator has been tasked by the boss to investigate the latest attack methods being used by a bad actor. Which of the following would be the BEST resource to use?\nA. MITRE ATT&CK\nB. A honeyfile\nC. A honeypot\nD. A CVE list", type: "story" },
            { text: "C. A honeypot is set up specifically to lure attackers so you can study their moves without risking your real systems.", type: "commentary" },
            { text: "2. What type of system is able to track users' access if the authentication method uses 802.1x?\nA. Federation Services\nB. Kerberos\nC. OAuth\nD. RADIUS", type: "story" },
            { text: "D. RADIUS is the go-to protocol for tracking user access in this scenario.", type: "commentary" },
            { text: "3. Which of the following can be used to provide non-repudiation?\nA. Asymmetric encryption\nB. Symmetric encryption\nC. A public key\nD. A SAML token", type: "story" },
            { text: "A. Asymmetric encryption (using digital signatures) proves exactly who sent the message. You can't deny it!", type: "commentary" },
            { text: "4. An international bank suffered an insider attack where $100,000 was pinched. The security team needs to find the culprit. Which is the BEST source of information?\nA. The system log\nB. The application log\nC. An audit trail\nD. The DNS log", type: "story" },
            { text: "C. An audit trail keeps a chronological record of who did what. It's the paper trail that catches the thief.", type: "commentary" },
            { text: "5. Which of the following security tools presents itself as a prized target, uses dummy data, and helps track attackers?\nA. Honeypot\nB. A honeyfile\nC. A honeytoken\nD. PAM", type: "story" },
            { text: "C. A honeytoken is a specific piece of fake data (like a fake database entry) that looks valuable but triggers an alarm when touched.", type: "commentary" },
            { text: "6. In corporate-speak, what process describes scrutinising the difference between existing resources and future aspirations?\nA. A SWOT analysis\nB. The capability maturity model\nC. Business process reengineering\nD. Gap analysis", type: "story" },
            { text: "D. Gap analysis is figuring out the \"gap\" between where you are and where you want to be.", type: "commentary" },
            { text: "7. Which of the following uses a private key to prove that an email hasn't been altered and definitely came from the sender?\nA. A digital signature\nB. Encryption\nC. Hashing\nD. DMARC", type: "story" },
            { text: "A. A digital signature handles integrity and non-repudiation.", type: "commentary" },
            { text: "8. Which intricate concept involves constantly tailoring user permissions based on evolving risk profiles and behaviour?\nA. A behavioural authentication framework\nB. Dynamic credential ciphering\nC. Adaptive identity management\nD. A cyber resilience protocol", type: "story" },
            { text: "C. Adaptive identity changes your access rights on the fly depending on where you are and what you're doing.", type: "commentary" },
            { text: "9. Which type of sensors can detect changes in frequency?\nA. Microwave sensors\nB. Pressure sensors\nC. Infrared sensors\nD. Ultrasonic sensors", type: "story" },
            { text: "A. Microwave sensors detect movement by measuring changes in frequency (Doppler effect).", type: "commentary" },
            { text: "10. Which of the following log files ensures that someone is responsible for another person?\nA. An IDS log\nB. A security log\nC. An event log\nD. A visitors log", type: "story" },
            { text: "D. A visitors log records who is on the premises and usually who is responsible for them (the host).", type: "commentary" },
            "CHAPTER 3: CHANGE MANAGEMENT (THE FUN POLICE)",
            { text: "Rewritten in Everyday Modern British English", type: "story" },
            { text: "This covers Exam Objective 1.3. Why we can't just change settings willy-nilly.", type: "commentary" },
            "INTRODUCTION",
            { text: "Change is inevitable, like rain on a Bank Holiday. But in IT, if you just change things without a plan, everything goes pear-shaped very quickly. Change Management is the boring but essential process of making sure updates don't break the whole company.", type: "story" },
            "THE PROCESS",
            { text: "You can't just decide to update the server because you feel like it. You have to follow the rules:", type: "story" },
            { text: "Approval Process: You have to ask permission. You write down what you want to do and why.", type: "story" },
            { text: "CAB (Change Advisory Board): A group of serious people (The Fun Police) who sit around a table and decide if your idea is brilliant or rubbish. They look at the risks and give the thumbs up (or down).", type: "story" },
            { text: "Ownership: Who is responsible? If it breaks, whose neck is on the block?", type: "story" },
            { text: "Impact Analysis: Asking \"What happens if we press this button?\" You need to know who will be affected.", type: "story" },
            { text: "Test Results: Prove it works. You test it in a sandbox first, not on the live system.", type: "story" },
            { text: "Backout Plan: The \"Undo\" button. If the update destroys the database, how do you go back to how it was 10 minutes ago? Crucial.", type: "story" },
            { text: "Maintenance Window: The time you're allowed to do the work. Usually 3 AM on a Sunday when nobody is working, so if you break it, nobody notices immediately.", type: "story" },
            "TECHNICAL IMPLICATIONS",
            { text: "Allow Lists / Deny Lists:", type: "story" },
            { text: "Allow List (Whitelist): Only these specific people/apps are allowed. Everyone else is barred. (Stricter).", type: "story" },
            { text: "Deny List (Blacklist): Everyone is allowed except these specific troublemakers.", type: "story" },
            { text: "Restricted Activities: Things you just aren't allowed to do, like installing games on the work PC.", type: "story" },
            { text: "Dependencies: Knowing that if you turn off Server A, Server B will also stop working because it relies on Server A. It's a domino effect.", type: "story" },
            "DOCUMENTATION (PAPERWORK)",
            { text: "If you didn't write it down, it didn't happen.", type: "story" },
            { text: "Network Diagrams: Maps of where all the cables and servers go. Keep them updated or you'll be lost.", type: "story" },
            { text: "Version Control: Keeping track of changes to code or documents (v1.0, v1.1, v2.0). Stops people overwriting each other's work.", type: "story" },
            "CHAPTER 3 REVIEW QUESTIONS (PUB QUIZ TIME)",
            { text: "1. What component of change management is essential for ensuring that security operations are not adversely affected by new implementations?\nA. Ownership\nB. Test results\nC. An approval process\nD. A backout plan", type: "story" },
            { text: "C. The approval process (specifically via the CAB) ensures that changes align with security goals before they happen.", type: "commentary" },
            { text: "2. Which of the following is the BEST solution for a cybersecurity team to implement to prevent employees from installing video games on company systems?\nA. Sandbox\nB. An allow list\nC. A block list\nD. Least privilege", type: "story" },
            { text: "B. An allow list (whitelist) is best because it only lets approved work apps run. Everything else (like games) is blocked by default.", type: "commentary" },
            { text: "3. When ensuring the accuracy of system representations, what practice reflects the actual network infrastructure?\nA. Regression testing\nB. Updating diagrams\nC. Data masking\nD. Version control", type: "story" },
            { text: "B. Updating diagrams ensures your maps match the territory.", type: "commentary" },
            { text: "4. What component of change management outlines the specific steps to be taken if a change goes belly up (fails)?\nA. A snapshot\nB. A backout plan\nC. A maintenance window\nD. Test results", type: "story" },
            { text: "B. A backout plan is your \"undo\" button to restore things to how they were.", type: "commentary" },
            { text: "5. When creating new software, what is the interconnection of services and system drivers known as?\nA. Errors in software code\nB. Incompatibilities\nC. Dependencies\nD. Interoperability", type: "story" },
            { text: "C. Dependencies are the things that rely on other things to work.", type: "commentary" },
            { text: "6. In IT operations, what is the primary reason for scheduling a maintenance window?\nA. To maximise resource utilisation\nB. To reduce the need for regular system backups\nC. To bypass the need for change management procedures\nD. To ensure updates are implemented without disrupting users", type: "story" },
            { text: "D. You do it at 3 AM so you don't disrupt users while they're working.", type: "commentary" },
            { text: "7. Which action involves closing and then reopening an application to refresh resources?\nA. An application refresh\nB. An application restart\nC. An application reload\nD. An application reset", type: "story" },
            { text: "B. An application restart. Have you tried turning it off and on again?", type: "commentary" },
            { text: "8. What is the main purpose of reviewing test results before deploying changes to a live environment?\nA. To validate user documentation\nB. To analyze system dependencies\nC. To confirm that a team adheres to coding standards\nD. To identify and address potential issues or defects", type: "story" },
            { text: "D. You test to find bugs before they break the live system.", type: "commentary" },
            { text: "9. What vital process in change management assesses the potential consequences of alterations?\nA. Impact analysis\nB. A backout plan\nC. A standard operating procedure\nD. A maintenance window", type: "story" },
            { text: "A. Impact analysis asks \"What will happen if we do this?\"", type: "commentary" },
            { text: "10. In a complex enterprise, what should be considered before executing a service restart to maintain availability?\nA. The temperature of the data centre\nB. The number of active user sessions\nC. The chronological order of code deployment\nD. The potential impact on interconnected services", type: "story" },
            { text: "D. You need to check the impact on interconnected services (dependencies) so you don't accidentally knock offline a service that relies on the one you're restarting.", type: "commentary" },
            "CHAPTER 4: CRYPTOGRAPHY (SECRET CODES)",
            { text: "Rewritten in Everyday Modern British English", type: "story" },
            { text: "This covers Exam Objective 1.4. Turning English into gobbledygook.", type: "commentary" },
            "INTRODUCTION",
            { text: "Cryptography isn't just for spies; it's how the internet works. It ensures your credit card details don't get nicked when you buy stuff online.", type: "story" },
            "PKI (PUBLIC KEY INFRASTRUCTURE)",
            { text: "This is the system of digital certificates that proves who people are.", type: "story" },
            { text: "Keys: Think of a lock and key.", type: "story" },
            { text: "Public Key: You give this to everyone. It's like your public address. People use it to encrypt a message to send to you.", type: "story" },
            { text: "Private Key: You keep this secret. Never share it. You use it to decrypt the messages people sent you. It's also used to sign things.", type: "story" },
            { text: "Key Escrow: Giving a copy of your key to a trusted third party (like the boss or a secure vault) just in case you get hit by a bus or forget your password.", type: "story" },
            "ENCRYPTION TYPES",
            { text: "Symmetric Encryption: Using the same key to lock and unlock the box. It's fast and good for large amounts of data. (Like AES).", type: "story" },
            { text: "Analogy: A house key. You use it to lock the door when you leave and unlock it when you return.", type: "story" },
            { text: "Asymmetric Encryption: Using a pair of keys (Public and Private). It's slower but safer for sharing keys.", type: "story" },
            { text: "Analogy: A postbox. Anyone can put a letter in (Public), but only the postman with the key can take letters out (Private).", type: "story" },
            "HASHING (DIGITAL FINGERPRINTS)",
            { text: "Hashing takes a file and turns it into a unique string of characters (like a1b2c3d4...).", type: "story" },
            { text: "One-Way: You can turn a file into a hash, but you can't turn the hash back into the file. You can't turn an omelette back into an egg.", type: "story" },
            { text: "Integrity: We use this to check if a file has changed. If you download a file and the hash matches the website's hash, you know it's the real deal and hasn't been tampered with.", type: "story" },
            { text: "Salting: Adding random data to a password before hashing it. It makes it much harder for hackers to crack passwords using \"Rainbow Tables\" (pre-computed lists of hashes).", type: "story" },
            "OBFUSCATION (HIDING IN PLAIN SIGHT)",
            { text: "Making things look confusing so hackers give up.", type: "story" },
            { text: "Steganography: Hiding secret data inside an innocent picture or music file. To the naked eye, it's a picture of a cat. To the spy, it's a blueprint.", type: "story" },
            { text: "Tokenization: Swapping real data (like a credit card number) for a random token. The shop stores the token, not your card details, so if they get hacked, the thieves just get useless tokens.", type: "story" },
            { text: "Data Masking: Hiding parts of data. Like on a receipt where it shows XXXX-XXXX-XXXX-1234.", type: "story" },
            "BLOCKCHAIN",
            { text: "A digital ledger (record book) that is shared across thousands of computers.", type: "story" },
            { text: "Immutable: Once you write something in the blockchain, you can't rub it out. It's permanent.", type: "story" },
            { text: "Decentralized: No single bank or person owns it. Everyone has a copy.", type: "story" },
            "CERTIFICATES",
            { text: "Digital ID cards for websites.", type: "story" },
            { text: "CA (Certificate Authority): The company that issues the ID card. They vouch for you. (Like the Passport Office).", type: "story" },
            { text: "Root of Trust: The top-level certificate that everything trusts.", type: "story" },
            { text: "CRL (Revocation List): A list of \"bad\" certificates that have been cancelled (maybe the key was stolen). Browsers check this list.", type: "story" },
            { text: "OCSP: A quicker way to check if a certificate is valid—it asks the CA in real-time, \"Is this cert still good?\"", type: "story" },
            { text: "Wildcard Certificate: One certificate that covers *.google.com. It works for mail.google.com, maps.google.com, etc. Save you buying loads of separate ones.", type: "story" },
            "CHAPTER 4 REVIEW QUESTIONS (PUB QUIZ TIME)",
            { text: "1. What is the primary purpose of a private key in a Public Key Infrastructure (PKI)?\nA. The encryption of sensitive data\nB. Storing cryptographic keys\nC. Encrypting messages for secure transmission\nD. Decryption and digital signatures", type: "story" },
            { text: "D. The private key is for decrypting messages sent to you and creating digital signatures.", type: "commentary" },
            { text: "2. Which type of encryption employs a single key to encrypt substantial volumes of data, utilising a block cipher technique?\nA. Hashing\nB. Asymmetric encryption\nC. Symmetric encryption\nD. A key exchange", type: "story" },
            { text: "C. Symmetric encryption uses one key and is fast enough for big data.", type: "commentary" },
            { text: "3. What technique involves transforming sensitive data, such as credit card numbers, into unique tokens that retain no intrinsic value?\nA. Obfuscation\nB. Salting\nC. Tokenization\nD. Steganography", type: "story" },
            { text: "C. Tokenization. It swaps the real data for a useless token.", type: "commentary" },
            { text: "4. Which cryptographic method involves utilising intricate mathematical operations to guarantee the irreversible transformation of data?\nA. Transport/communication encryption\nB. Asymmetric encryption\nC. A key exchange\nD. Algorithm encryption", type: "story" },
            { text: "D. This refers to algorithms (specifically hashing, usually, but in this context \"Algorithm encryption\" is the source text's choice for the math behind it). Note: The question text is slightly ambiguous but 'D' is the intended answer in the source context.", type: "commentary" },
            { text: "5. What term is used to describe the catalogs that contain invalidated digital certificates?\nA. Self-signed\nB. Certificate signing request (CSR) generation\nC. Certificate authorities\nD. Certificate revocation lists (CRLs)/the Online Certificate Status Protocol (OCSP)", type: "story" },
            { text: "D. CRLs are the lists of banned certificates.", type: "commentary" },
            { text: "6. What do you need to securely store cryptographic keys within a hardware device, AND which encryption level involves converting entire disks? (Choose TWO).\nA. A Trusted Platform Module (TPM) chip\nB. A Hardware Security Module (HSM)\nC. Encryption key management software\nD. Password-based encryption\nE. Full-Disk Encryption (FDE)", type: "story" },
            { text: "A and E. You generally use a TPM to store the keys for Full-Disk Encryption (FDE).", type: "commentary" },
            { text: "7. What does a key exchange involve in cryptography?\nA. Encrypting large amounts of data using a single key\nB. Securely transmitting cryptographic keys\nC. Ensuring encryption irreversibility\nD. Utilising private and public keys for decryption", type: "story" },
            { text: "B. It's the secure method of getting the keys from A to B.", type: "commentary" },
            { text: "8. What type of digital certificate is self-generated, lacks third-party validation, and is typically used for internal servers to save costs?\nA. A wildcard\nB. Certificate authorities\nC. Certificate signing request (CSR) generation\nD. Self-signed", type: "story" },
            { text: "D. Self-signed. Fine for internal stuff, but gives warnings on the public web.", type: "commentary" },
            { text: "9. What technology serves as a decentralized digital ledger, ensuring secure and tamper-resistant records?\nA. Encryption\nB. Digital signatures\nC. Blockchain\nD. Proof of work", type: "story" },
            { text: "C. Blockchain. The distributed ledger.", type: "commentary" },
            { text: "10. Which technique involves the strategic act of deliberately obscuring code to make it difficult to understand?\nA. Obfuscation\nB. Tokenization\nC. Steganography\nD. Data masking", type: "story" },
            { text: "A. Obfuscation. Making the code look like spaghetti so hackers can't read it.", type: "commentary" },
        ]
    },
    "gulistan": {
        title: "The Gulistan",
        content: [
            "THE GULISTAN",
            "(THE ROSE GARDEN)",
            { text: "Rewritten in Everyday Modern British English. Note: This version uses common British idioms and slang to help you learn how native speakers talk today.", type: "commentary" },
            "CHAPTER I: ON THE MANNERS OF KINGS",
            "STORY I",
            { text: "I once heard of a king who ordered a prisoner to be put to death. The poor bloke, having absolutely nothing left to lose, started giving the King a proper earful, swearing and slagging him off. As the saying goes: \"Anyone who washes their hands of life says whatever is in their heart.\"", type: "story" },
            { text: "The King asked: \"What's he going on about?\"", type: "story" },
            { text: "A Good-Hearted Minister: \"My Lord, he's quoting a holy verse: 'Paradise is waiting for those who keep their temper and forgive others, for God loves a decent sort.'\"", type: "story" },
            { text: "The King felt gutted for the man and decided to let him off the hook.", type: "story" },
            { text: "A Rival Minister: \"It's not right for people like us to tell porkies (lies) to a king. That prisoner was actually cursing you and calling you all sorts of names.\"", type: "story" },
            { text: "The King frowned at this rival. \"I prefer that man's lie to your truth,\" the King said. \"His lie was meant to keep the peace, but your truth was just stirring the pot. As wise men say: 'A lie that sorts things out is better than a truth that causes a ruckus.'\"", type: "story" },
            { text: "Sometimes, being brutally honest just to cause trouble is worse than telling a \"fib\" to save someone's neck. The King valued mercy over being technically correct.", type: "commentary" },
            "STORY II",
            { text: "A king named Mahmud Sabuktagin appeared in a dream a hundred years after he'd popped his clogs (died). His body had turned to dust, but his eyes were still moving in their sockets, having a gander (look) around.", type: "story" },
            { text: "None of the clever clogs (wise men) could explain it, except for a poor dervish. He bowed and said: \"His eyes are still looking around because he's worried his kingdom has been taken over by some other geezer.\"", type: "story" },
            { text: "This shows that power-hungry people can't let go, even after they're dead. The King was so attached to his throne he couldn't rest in peace.", type: "commentary" },
            "STORY III",
            { text: "A prince was born extremely titchy (short) and plain, while all his brothers were tall and handsome. One day, his dad looked at him like he was a bit of a disappointment.", type: "story" },
            { text: "The lad was sharp as a tack and said: \"Dad, a clever dwarf is better than a daft giant. Bigger isn't always better. A sheep is clean and useful, but an elephant is just a massive lump.\"", type: "story" },
            { text: "The father had a chuckle, and the advisors agreed, but the brothers were green with envy. Later, in a scrap (battle), this short prince was the first to charge in, fighting like a lion while the others were bricking it (scared). He led the army to a win.", type: "story" },
            { text: "The King was chuffed to bits (very pleased) and made him his heir. The brothers were so jealous they tried to spike his food with poison. His sister saw them from a window and banged the shutters shut to warn him. The prince twigged (understood) what was happening and didn't eat. He said: \"It's impossible for talented blokes to die just so useless ones can take their place.\"", type: "story" },
            { text: "Size doesn't matter; brains and bottle (courage) do. Also, success breeds jealousy, even in your own family.", type: "commentary" },
            "STORY IV",
            { text: "A gang of yobs (hooligans) lived on a mountain top. They were causing a right mess, robbing caravans and fighting off the King's soldiers. The King's advisors decided they had to sort them out before they got too big for their boots.", type: "story" },
            { text: "Soldiers hid and waited until the yobs were fast asleep. They nicked (captured) the lot of them. The King ordered them all to be executed.", type: "story" },
            { text: "However, there was one young lad among them. A kind minister begged the King: \"This lad is only a nipper. Please let him off. I'll raise him, educate him, and make him a proper gentleman.\"", type: "story" },
            { text: "The King said: \"A bad egg is a bad egg. You can't turn a wolf into a pet dog.\"", type: "story" },
            { text: "But the minister kept badgering him, so the King agreed. The minister raised the boy, and for two years, he seemed sound. But eventually, the lad joined a gang of rough sorts, killed the minister and his two sons, pinched (stole) their cash, and went back to being a bandit.", type: "story" },
            { text: "The King heard this and said: \"I told you so. You can't make a silk purse out of a sow's ear.\"", type: "story" },
            { text: "Some people believe \"nature\" (what you're born as) is stronger than \"nurture\" (how you're raised). If someone's rotten to the core, school won't fix them.", type: "commentary" },
            "STORY V",
            { text: "I saw a young chap at the palace who was dead clever and handsome. Everyone fancied him, except the jealous lot who tried to frame him for treason.", type: "story" },
            { text: "The King asked him: \"Why have they got it in for you?\"", type: "story" },
            { text: "The lad replied: \"I can keep everyone else happy, but I can never please a jealous person. The only time they're happy is when I'm in the gutter.\"", type: "story" },
            { text: "You can't reason with envy. Envious people only cheer up when you fail.", type: "commentary" },
            "STORY VI",
            { text: "A Persian King was a nasty piece of work. He fleeced (robbed) his people and treated them like dirt. The people got fed up and legged it (left) to other countries. Because the population dropped, the tax money dried up, and the King became skint (broke) and weak.", type: "story" },
            { text: "A minister told the King: \"To be a strong King, you need people. If you're cruel, they'll do a runner. You can't be a shepherd if you scare off the sheep.\"", type: "story" },
            { text: "The King threw a wobbly (got angry) and chucked the minister in the clink (prison). Soon after, the King's cousins started a rebellion. Because the people hated the King, they sided with the cousins, and the King got the sack (lost his job/throne).", type: "story" },
            { text: "A leader's power comes from the people. If you treat them badly, they'll turn on you the moment they get the chance.", type: "commentary" },
            "STORY VII",
            { text: "A King was on a ship with a Persian slave who'd never been to sea. The slave was petrified, crying and shaking. He was doing everyone's head in.", type: "story" },
            { text: "A wise chap on the boat said, \"I can shut him up if you let me.\" The King said, \"Go on then.\"", type: "story" },
            { text: "The wise man told the crew to chuck the slave into the sea. The slave swallowed a load of water and panicked. They dragged him back by his hair. He climbed back on board and sat in the corner, quiet as a mouse.", type: "story" },
            { text: "The King asked, \"Why did that work?\"", type: "story" },
            { text: "The wise man replied: \"He didn't realise how cushy the boat was until he tasted the danger of drowning. We only appreciate being safe when we've been in a spot of bother.\"", type: "story" },
            { text: "We take things for granted. Sometimes you need a bit of hardship to appreciate how good you've got it.", type: "commentary" },
            "STORY VIII",
            { text: "A King named Hurmuz locked up his dad's ministers. Someone asked, \"What did they do wrong?\"", type: "story" },
            { text: "Hurmuz replied, \"Nothing really. But I saw they were scared stiff of me. Because they were scared, I worried they might try to bump me off just to be safe. As the saying goes: 'A cat will scratch a leopard's eyes out if it's cornered.' I got in there first.\"", type: "story" },
            { text: "Fear makes people dangerous. If someone is terrified of you, they might hurt you just to protect themselves. The King was being proactive.", type: "commentary" },
            "STORY IX",
            { text: "An old Arab King was on his last legs. A messenger ran in shouting, \"Great news! We've taken the castle and beaten the enemy!\"", type: "story" },
            { text: "The King sighed: \"That's not good news for me, mate. It's good news for my heirs. I'm on my way out.\"", type: "story" },
            { text: "Winning wars means nothing when you're about to die. He realised he'd spent his life chasing things he couldn't take with him.", type: "commentary" },
            "STORY X",
            { text: "I was praying at a mosque in Damascus near John the Baptist's tomb. A famously cruel King came to pray. He asked me, \"Say a prayer for me, will you? I'm worried about a powerful enemy.\"", type: "story" },
            { text: "I told him: \"If you want help, be kind to your own people. It's no good crushing the poor with one hand and asking God for a favour with the other. If you don't listen to your people, why should God listen to you?\"", type: "story" },
            { text: "You can't be a tyrant and expect God to bail you out. What goes around comes around.", type: "commentary" },
            "STORY XI",
            { text: "A holy man visited Baghdad. A hated governor asked him, \"Do a good prayer for me.\"", type: "story" },
            { text: "The holy man prayed: \"Oh God, please let him cark it (die).\"", type: "story" },
            { text: "The governor was shocked. \"How is that a good prayer?\"", type: "story" },
            { text: "The holy man replied: \"It's good for you (because you stop sinning) and it's brilliant for the people (because they're shot of you).\"", type: "story" },
            { text: "For a wicked person, death is actually a blessing because it stops them doing more damage.", type: "commentary" },
            "STORY XII",
            { text: "A cruel King asked a holy man, \"What's the best way for me to worship?\"", type: "story" },
            { text: "The holy man said: \"Having a kip (sleeping) at noon.\"", type: "story" },
            { text: "The King asked why. The holy man replied: \"Because while you're asleep, you aren't bothering anyone.\"", type: "story" },
            { text: "The best thing a bad leader can do is nothing. When they're inactive, everyone else gets a break.", type: "commentary" },
            "STORY XIII",
            { text: "A King was absolutely sloshed (drunk) and feeling great. He shouted, \"I haven't got a care in the world! I'm top of the world!\"", type: "story" },
            { text: "A naked beggar outside in the cold heard him and said, \"Alright for you, isn't it? What about us poor sods?\"", type: "story" },
            { text: "The King felt bad and chucked a bag of gold out the window. The beggar caught it. But, being a bit hopeless with money, he blew the lot in a few days and came back begging.", type: "story" },
            { text: "The King was fuming and wanted to chase him off. A wise advisor said: \"Don't be violent, it looks bad. But don't give him a lump sum again. Give him a small allowance so he doesn't piss it up the wall (waste it).\"", type: "story" },
            { text: "Throwing money at a foolish person doesn't help. Regular, small help is better. Also, leaders shouldn't be moody—generous one minute, angry the next.", type: "commentary" },
            "STORY XIV",
            { text: "A King was a bit tight (stingy). He didn't pay his soldiers properly. When a strong enemy attacked, the soldiers legged it.", type: "story" },
            { text: "I told a mate, \"It's out of order to leave your boss in the lurch.\"", type: "story" },
            { text: "The mate replied, \"If the King doesn't give us cash for grub, we can't fight. You fight for a bloke who pays you. If the King is cheap, we're off.\"", type: "story" },
            { text: "Loyalty works both ways. If an employer treats staff like rubbish, they can't expect loyalty when things go wrong.", type: "commentary" },
            "STORY XV",
            { text: "A minister got the sack and became a monk to live a quiet life. The King later wanted him back. The minister said, \"No thanks. It's better to be unemployed than in charge.\"", type: "story" },
            { text: "He explained that while a quiet life is poor, it's safe. Working for a King is dodgy—sometimes you get gold, sometimes you lose your head.", type: "story" },
            { text: "High-up jobs come with stress and danger. A simple life is less hassle.", type: "commentary" },
            "STORY XVI",
            { text: "A mate complained he was skint and had too many kids. He wanted to move abroad. But he was worried people would take the mickey (make fun of him). He asked me to get him a government job.", type: "story" },
            { text: "I told him: \"Government work has two sides: plenty of dosh (money) or losing your life. Is it worth the hassle?\"", type: "story" },
            { text: "He got stroppy and said I wasn't being a good mate. So, I got him a small job. He did well and got promoted. Eventually, he became a big cheese.", type: "story" },
            { text: "Later, I found him in prison, in chains. The King had turned on him. I said, \"I warned you. If you hadn't taken the job, you'd be broke, but you wouldn't be in this mess.\"", type: "story" },
            { text: "Ambition is risky. My friend wanted the rewards but ignored the danger. The higher you climb, the harder you fall.", type: "commentary" },
            "STORY XVII",
            { text: "Some of my mates lost their pension because of one mistake. I went to speak to the Prince for them. The guard was a bit cheeky, but I waited.", type: "story" },
            { text: "When I finally saw the Prince, I asked him to let them off. I said, \"God provides for everyone, even sinners. You should be like that too.\"", type: "story" },
            { text: "The Prince liked my patter and gave them their money back.", type: "story" },
            { text: "You should back your mates when they're in trouble. Also, being polite works better than demanding things.", type: "commentary" },
            "STORY XVIII",
            { text: "A Prince inherited a fortune and gave it all away to soldiers and the poor. An advisor said, \"Pack it in! You need to save that cash for a rainy day.\"", type: "story" },
            { text: "The Prince replied, \"God made me a King to give, not to guard the safe. I'm not a security guard.\"", type: "story" },
            { text: "True generosity means helping others, not hoarding cash.", type: "commentary" },
            "STORY XIX",
            { text: "King Nushirwan was on a hunting trip. They were roasting meat but had no salt. A servant went to a village to get some.", type: "story" },
            { text: "The King shouted, \"Make sure you pay for the salt! Don't nick it!\"", type: "story" },
            { text: "His men asked, \"Why? It's hardly worth anything.\"", type: "story" },
            { text: "The King replied, \"Tyranny starts with small things. If the King takes an apple for free, his soldiers will uproot the whole tree. If I take five eggs, my army will roast a thousand chickens.\"", type: "story" },
            { text: "Corruption starts small. If the boss bends the rules a tiny bit, the staff will smash them. A leader has to set a proper example.", type: "commentary" },
            "STORY XX",
            { text: "A tax collector was squeezing the peasants dry to get money for the Sultan. He didn't realise that if you hurt people to please the boss, God will get you in the end.", type: "story" },
            { text: "The King found out the collector was cruel and had him tortured.", type: "story" },
            { text: "Even if you're \"just following orders\", cruelty will come back to bite you.", type: "commentary" },
            "STORY XXI",
            { text: "A bully hit a holy man on the head with a stone. The holy man couldn't fight back, so he kept the stone.", type: "story" },
            { text: "Years later, the bully fell out of favour and was thrown in a pit by the King. The holy man went to the pit and chucked the stone at him.", type: "story" },
            { text: "The bully asked, \"Who are you?\"", type: "story" },
            { text: "The man said, \"I'm the bloke you hit years ago. I waited until you were down on your luck to get my own back.\"", type: "story" },
            { text: "When your enemy is strong, keep your head down. Wait until they're weak to get justice.", type: "commentary" },
            "STORY XXII",
            { text: "A King had a nasty illness. Doctors said the only cure was the bile of a specific type of child. They found a farm boy who fit the bill.", type: "story" },
            { text: "The King paid the parents a fortune, and they agreed to sell their son. The judge signed a paper saying it was legal to kill the lad to save the King.", type: "story" },
            { text: "Just as the executioner raised the sword, the boy smiled.", type: "story" },
            { text: "The King asked, \"What's funny?\"", type: "story" },
            { text: "The boy said: \"A kid looks to parents for love, to the judge for justice, and to the King for mercy. But my parents sold me for cash, the judge ordered my death, and the King wants to eat me to live. I've got no one left but God.\"", type: "story" },
            { text: "The King was heartbroken. He cried, kissed the boy, and let him go. \"Better for me to die than spill innocent blood,\" he said. Amazingly, the King got better that very week.", type: "story" },
            { text: "The boy shamed the King into doing the right thing. Showing mercy can bring good karma.", type: "commentary" },
            "STORY XXIII",
            { text: "A slave did a runner. When he was caught, the Minister (who hated the slave) told the King to execute him as a warning.", type: "story" },
            { text: "The slave said: \"Fair enough, kill me. But I don't want you to get in trouble with God for it. Let me kill this nasty Minister first. Then you can execute me for murder. That way, it's all legal.\"", type: "story" },
            { text: "The King laughed. He asked the Minister, \"What do you reckon?\"", type: "story" },
            { text: "The Minister said, \"For heaven's sake, let him go! I don't want to die just to get him in trouble. I dug a hole for him and fell in it myself.\"", type: "story" },
            { text: "If you try to destroy someone else, it might backfire on you.", type: "commentary" },
            "STORY XXIV",
            { text: "A Minister was banged up (imprisoned) by his King. Because the Minister had always been decent to the guards, they made his time inside bearable.", type: "story" },
            { text: "He tried to send a secret letter, but it was intercepted. The King was fuming and accused him of treason.", type: "story" },
            { text: "The Minister read the letter to the King. It said: \"The King is angry with me, but I can't badmouth him because he's been good to me in the past.\"", type: "story" },
            { text: "The King realised the Minister was loyal even when he was in the doghouse. He forgave him.", type: "story" },
            { text: "Being nice pays off. Because the Minister was kind to the guards, they looked after him. Because he was loyal, he got his freedom.", type: "commentary" },
            "STORY XXV",
            { text: "A King doubled a servant's wages. Why? Because that servant was always grafting (working hard), while others were messing about.", type: "story" },
            { text: "A wise man said: \"That's how God works too. If you put the work in, you get the rewards.\"", type: "story" },
            { text: "Success goes to the grafters, not the slackers.", type: "commentary" },
            "STORY XXVI",
            { text: "A tyrant used to force poor people to sell him wood cheap, then sold it to the rich for a fortune.", type: "story" },
            { text: "A holy man warned him: \"You're like a snake in the grass. Watch out, the poor will get you in the end.\"", type: "story" },
            { text: "The tyrant ignored him. One night, a fire started in his kitchen and burned his palace to the ground. The holy man said, \"The fire came from the burning hearts of the poor.\"", type: "story" },
            { text: "What goes around comes around. If you rip people off, you'll lose everything eventually.", type: "commentary" },
            "STORY XXVII",
            { text: "A master wrestler knew 360 tricks. He taught his favourite student 359 of them, but kept one up his sleeve.", type: "story" },
            { text: "The student got cocky. He told the King, \"I'm stronger than my master. I only let him win out of respect.\"", type: "story" },
            { text: "The King ordered a match. The student charged in like a bull. The master used the one secret trick he'd saved. He threw the student to the ground easily.", type: "story" },
            { text: "The master said: \"I saved this for a rainy day. Never give a mate so much power they can crush you if they turn on you.\"", type: "story" },
            { text: "Always keep a bit back for yourself. People can turn on you, so don't give away all your advantages.", type: "commentary" },
            "STORY XXVIII",
            { text: "A dervish was sitting in the desert. A King passed by, but the dervish didn't bat an eyelid. The King was offended and called him an animal.", type: "story" },
            { text: "The dervish said: \"Kings are there to protect people, like shepherds protect sheep. Sheep aren't there to wait on the shepherd.\"", type: "story" },
            { text: "The King was impressed and asked for advice. The dervish said: \"Remember, your wealth will pass to someone else when you snuff it, just as you got it from someone else.\"", type: "story" },
            { text: "Power is a duty. Leaders serve the people. Also, you can't take it with you when you go.", type: "commentary" },
            "STORY XXIX",
            { text: "A Minister went to a religious bloke and said, \"I serve the King day and night, hoping for a pay rise and fearing his temper.\"", type: "story" },
            { text: "The religious man wept and said: \"If I feared God as much as you fear the King, I'd be a saint.\"", type: "story" },
            { text: "We worry more about pleasing our bosses than living by our principles.", type: "commentary" },
            "STORY XXX",
            { text: "A King ordered an innocent man to be killed. The man said, \"King, don't hurt yourself by hurting me.\"", type: "story" },
            { text: "\"How am I hurting myself?\" the King asked.", type: "story" },
            { text: "The man replied: \"My pain will be over in a second. But your guilt will last forever.\"", type: "story" },
            { text: "The King let him go.", type: "story" },
            { text: "Doing wrong hurts the sinner's soul more than the victim's body.", type: "commentary" },
            "STORY XXXI",
            { text: "The King and his ministers were debating. One wise minister, Buzurchimihr, waited to see what the King thought, then agreed with him.", type: "story" },
            { text: "Others asked him, \"Why did you just agree with the boss?\"", type: "story" },
            { text: "He replied, \"Because nobody knows the answer for sure. If we get it wrong, but I agreed with the King, he can't have a go at me. It's safer to agree with the big cheese.\"", type: "story" },
            { text: "A cynical lesson: sometimes you just say \"yes\" to the boss to save your own skin.", type: "commentary" },
            "STORY XXXII",
            { text: "A traveller pretended to be related to the Prophet to get respect and cash. He claimed to have written a famous poem.", type: "story" },
            { text: "The King found out he was telling porkies about everything. The King ordered him to be beaten.", type: "story" },
            { text: "The liar said, \"I'll tell one true thing. If it's a lie, you can kill me.\"", type: "story" },
            { text: "The King asked what it was.", type: "story" },
            { text: "The man said: \"If a poor man brings you yoghurt, it's mostly water. If a traveller tells you stories, they're mostly rubbish.\"", type: "story" },
            { text: "The King laughed at his honesty and gave him some cash anyway.", type: "story" },
            { text: "The man saved himself by admitting that desperate people have to lie to survive. A bit of banter can save your neck.", type: "commentary" },
            "STORY XXXIII",
            { text: "A kind Minister got on the wrong side of the King. Because he'd been so sound to everyone in the past, everyone put in a good word for him. He was soon forgiven.", type: "story" },
            { text: "Be nice to people on your way up, you might need them on your way down.", type: "commentary" },
            "STORY XXXIV",
            { text: "The son of the Caliph Harun complained: \"Someone was rude about my mum!\"", type: "story" },
            { text: "Harun asked his advisors what to do. They suggested killing the guy or banishing him.", type: "story" },
            { text: "Harun said to his son: \"The bigger man would forgive him. If you can't forgive him, then say something rude back—but don't go over the top, or you're just as bad.\"", type: "story" },
            { text: "Don't hold a grudge. If you must respond, keep it proportionate.", type: "commentary" },
            "STORY XXXV",
            { text: "A boat sank. Two brothers were drowning. A rich man offered a sailor a tenner to save them. The sailor pulled one out, but the other drowned.", type: "story" },
            { text: "The sailor said: \"I really wanted to save this one because once, in the desert, he gave me a lift. The other brother once whipped me.\"", type: "story" },
            { text: "Good deeds save you; bad deeds come back to haunt you.", type: "commentary" },
            "STORY XXXVI",
            { text: "Two brothers: one was a rich servant to the Sultan, the other was a poor labourer.", type: "story" },
            { text: "The rich brother said: \"Why don't you serve the Sultan and stop grafting so hard?\"", type: "story" },
            { text: "The poor brother said: \"Why don't you work hard so you can stop being a servant? It's better to eat basic bread and sit on the floor than to wear a golden belt and be someone's lackey.\"", type: "story" },
            { text: "Independence is worth more than luxury. Better to be poor and free than rich and owned.", type: "commentary" },
            "STORY XXXVII",
            { text: "Someone told King Nushirwan, \"Good news! Your enemy has popped his clogs.\"", type: "story" },
            { text: "The King replied, \"Is there any news that I'm going to live forever?\"", type: "story" },
            { text: "Don't cheer when an enemy dies. We're all heading the same way eventually.", type: "commentary" },
            "STORY XXXVIII",
            { text: "A council was chatting. A wise man stayed quiet.", type: "story" },
            { text: "They asked, \"Why aren't you speaking?\"", type: "story" },
            { text: "He said, \"Ministers are like doctors. Doctors only give medicine to the sick. I see your ideas are spot on, so I don't need to chip in. I only speak when I see a blind man walking into a hole.\"", type: "story" },
            { text: "Don't talk just for the sake of it. Only give advice when it's actually needed.", type: "commentary" },
            "STORY XXXIX",
            { text: "The Caliph Harun conquered Egypt. To insult the memory of the arrogant Pharaohs, he gave the job of governor to his thickest slave.", type: "story" },
            { text: "The slave was so daft he told farmers to plant wool instead of cotton so it wouldn't rot.", type: "story" },
            { text: "Sometimes wealth and power are given to complete muppets. Rank doesn't mean intelligence.", type: "commentary" },
            "STORY XL",
            { text: "A King tried to hug a beautiful Chinese girl, but she pushed him away. In a huff, he gave her to a hideous slave who smelled awful.", type: "story" },
            { text: "Later, the King missed the girl and wanted her back.", type: "story" },
            { text: "A witty minister told him: \"A thirsty man doesn't care if the water comes from a dirty cup. But you probably don't want the water after someone with a minging (dirty/smelly) mouth has drunk from it.\"", type: "story" },
            { text: "The King decided to let the slave keep her.", type: "story" },
            { text: "Once you've chucked something away in anger, you can't always get it back. The King's temper cost him something he wanted.", type: "commentary" },
            "STORY XLI",
            { text: "People asked Alexander the Great: \"How did you conquer the world when other Kings had more cash and soldiers?\"", type: "story" },
            { text: "He replied: \"I never bullied the people I conquered, and I never slagged off other Kings.\"", type: "story" },
            { text: "True greatness comes from being fair and generous, not just from brute force.", type: "commentary" },
        ]
    }
};

